module FedexSMS
  class FieldRegistry
    def initialize(field_specs)
      @fields_by_id = {}
      @fields_by_description = {}

      field_specs.each do |field_spec|
        field = FieldSpec.new(*field_spec)
        @fields_by_id[field.id] = field
        @fields_by_description[field.description] = field
      end
    end

    def fetch(key, &blk)
      case key
      when Numeric then @fields_by_id.fetch(key, &blk)
      when String  then @fields_by_description.fetch(key, &blk)
      else
        raise ArgumentError, "Invalid registry key: #{key.inspect}"
      end
    end
  end

  FIELD_REGISTRY = FieldRegistry.new([
    [0   , "N"  , false, 0..3  , nil, "TRANSACTION CODE"],
    [1   , "A"  , false, 0..30 , nil, "CUSTOMER TRANSACTION IDENTIFIER"],
    [2   , "A"  , false, 0..4  , nil, "ERROR CODE"],
    [3   , "A"  , false, 0..80 , nil, "ERROR MESSAGE"],
    [4   , "A"  , false, 0..35 , nil, "SENDER COMPANY"],
    [5   , "A"  , false, 0..35 , nil, "SENDER ADDRESS LINE 1"],
    [6   , "A"  , false, 0..35 , nil, "SENDER ADDRESS LINE 2"],
    [7   , "A"  , false, 0..35 , nil, "SENDER CITY"],
    [8   , "A"  , false, 0..2  , nil, "SENDER STATE/PROVINCE"],
    [9   , "A"  , false, 0..10 , nil, "SENDER POSTAL CODE"],
    [10  , "N"  , false, 0..9  , nil, "SENDER FEDEX EXPRESS ACCOUNT NUMBER"],
    [11  , "A/N", false, 0..35 , nil, "RECIPIENT COMPANY"],
    [12  , "A"  , false, 0..35 , nil, "RECIPIENT CONTACT NAME"],
    [13  , "A/N", false, 0..35 , nil, "RECIPIENT ADDRESS LINE 1"],
    [14  , "A"  , false, 0..35 , nil, "RECIPIENT ADDRESS LINE 2"],
    [15  , "A"  , false, 0..35 , nil, "RECIPIENT CITY"],
    [16  , "A"  , false, 0..14 , nil, "RECIPIENT STATE/PROVINCE"],
    [17  , "A/N", false, 0..10 , nil, "RECIPIENT POSTAL CODE"],
    [18  , "N"  , false, 0..15 , nil, "RECIPIENT PHONE NUMBER"],
    [20  , "N"  , false, 0..9  , nil, "PAYOR ACCOUNT NUMBER"],
    [21  , "N"  , false, 0..8  , 1  , "PACKAGE WEIGHT"],
    [23  , "N"  , false, 0..1  , nil, "PAY TYPE"],
    [24  , "N"  , false, 0..8  , nil, "SHIP DATE"],
    [25  , "A/N", true , 0..39 , nil, "CUSTOMER REFERENCE"],
    [26  , "N"  , true , 0..11 , nil, "DECLARED VALUE/CARRIAGE VALUE"],
    [27  , "A"  , true , 0..1  , nil, "C.O.D. FLAG"],
    [28  , "N"  , false, 0..15 , nil, "C.O.D. RETURN TRACKING NUMBER"],
    [29  , "A"  , true , 0..25 , nil, "TRACKING NUMBER"],
    [30  , "A"  , false, 0..8  , nil, "URSA CODE"],
    [32  , "A"  , false, 0..35 , nil, "SENDER CONTACT NAME"],
    [33  , "A"  , false, 0..2  , nil, "SERVICE COMMITMENT CODE"],
    [34  , "N"  , true , 0..11 , 2  , "BASE CHARGE"],
    [35  , "N"  , true , 0..11 , 2  , "TOTAL SURCHARGE AMOUNT"],
    [36  , "N"  , true , 0..11 , 2  , "TOTAL DISCOUNT AMOUNT"],
    [37  , "N"  , true , 0..11 , 2  , "NET CHARGE"],
    [38  , "A"  , false, 0..35 , nil, "SENDER/ORIGIN DEPARTMENT"],
    [40  , "A"  , false, 0..1  , nil, "FIELD 40"],
    [41  , "A"  , false, 0..2  , nil, "FIELD 41"],
    [42  , "N"  , false, 0..9  , 3  , "FIELD 42"],
    [43  , "N"  , false, 0..3  , 1  , "FIELD 43"],
    [44  , "A"  , false, 0..35 , nil, "HAL ADDRESS"],
    [46  , "A"  , false, 0..35 , nil, "HAL CITY"],
    [47  , "A"  , false, 0..2  , nil, "HAL STATE"],
    [48  , "A"  , false, 0..10 , nil, "HAL POSTAL CODE"],
    [49  , "N"  , false, 0..15 , nil, "HAL CONTACT PHONE NUMBER"],
    [50  , "A"  , true , 0..2  , nil, "RECIPIENT COUNTRY"],
    [51  , "A"  , false, 0..1  , nil, "SIGNATURE RELEASE"],
    [52  , "N"  , false, 0..3  , nil, "FIELD 52"],
    [53  , "N"  , true , 0..10 , 2  , "C.O.D. COLLECT AMOUNT"],
    [54  , "A"  , false, 0..1  , nil, "C.O.D. CASHIERS CHECK OR MONEY ORDER"],
    [55  , "N"  , false, 0..5  , nil, "BUNDLE NUMBER"],
    [56  , "N"  , false, 0..9  , nil, "INVOICE NUMBER"],
    [57  , "N"  , true , 0..3  , nil, "PACKAGE HEIGHT"],
    [58  , "N"  , true , 0..3  , nil, "PACKAGE WIDTH"],
    [59  , "N"  , true , 0..3  , nil, "PACKAGE LENGTH"],
    [60  , "N"  , false, 0..9  , 1  , "BILLED WEIGHT"],
    [65  , "A"  , false, 0..32 , nil, "ASTRA BAR CODE"],
    [66  , "A"  , false, 0..30 , nil, "BROKER NAME"],
    [67  , "N"  , false, 0..15 , nil, "BROKER PHONE NUMBER"],
    [68  , "A"  , false, 0..3  , nil, "CUSTOMS CURRENCY TYPE"],
    [69  , "N"  , false, 0..14 , 2  , "DECLARED VALUE/CARRIAGE VALUE"],
    [70  , "N"  , false, 0..1  , nil, "DUTY/TAX PAYMENT TYPE"],
    [71  , "N"  , false, 0..9  , nil, "DUTY/TAX PAYOR ACCOUNT NUMBER"],
    [72  , "N"  , false, 0..1  , nil, "TERMS OF SALE"],
    [73  , "A"  , false, 0..1  , nil, "PARTIES RELATED"],
    [74  , "A"  , false, 0..2  , nil, "COUNTRY OF ULTIMATE DESTINATION"],
    [75  , "A"  , false, 0..3  , nil, "WEIGHT UNITS"],
    [76  , "N"  , false, 0..5  , nil, "NUMBER OF PACKAGES"],
    [77  , "N"  , true , 0..8  , 1  , "COMMODITY LINE ITEM WEIGHT"],
    [78  , "N"  , true , 0..9  , 2  , "COMMODITY CUSTOMS VALUE"],
    [79  , "AKE", true , 0..450, nil, "DESCRIPTION OF CONTENTS"],
    [80  , "A"  , true , 0..2  , nil, "COUNTRY OF MANUFACTURE"],
    [81  , "A"  , true , 0..10 , nil, "HARMONIZED CODE"],
    [82  , "N"  , true , 0..7  , nil, "COMMODITY QUANTITY"],
    [83  , "A"  , false, 0..12 , nil, "EXPORT LICENSE NUMBER"],
    [84  , "N"  , false, 0..8  , nil, "LICENSE EXPIRATION DATE"],
    [99  , "A"  , false, 0..0  , nil, "END OF RECORD INDICATOR"],
    [112 , "N"  , true , 0..8  , 1  , "TOTAL SHIPMENT WEIGHT"],
    [113 , "A"  , false, 0..1  , nil, "COMMERCIAL INVOICE PRINT AND UPLOAD FLAG"],
    [116 , "N"  , false, 0..4  , nil, "PACKAGE TOTAL"],
    [117 , "A"  , false, 0..2  , nil, "SENDER COUNTRY CODE"],
    [118 , "A"  , false, 0..18 , nil, "RECIPIENT IRS/EIN/VAT/EORI NUMBER"],
    [119 , "N"  , false, 0..11 , 2  , "TOTAL COMMODITY CUSTOMS VALUE"],
    [120 , "A"  , true , 0..15 , nil, "MARKS AND NUMBERS"],
    [168 , "A"  , false, 0..10 , nil, "IMPORTER OF RECORD - BUSINESS CODE"],
    [169 , "A"  , false, 0..2  , nil, "IMPORTER OF RECORD - COUNTRY CODE"],
    [170 , "A"  , false, 0..35 , nil, "IMPORTER OF RECORD - CONTACT NAME"],
    [171 , "A"  , false, 0..35 , nil, "IMPORTER OF RECORD - COMPANY NAME"],
    [172 , "A"  , false, 0..35 , nil, "IMPORTER OF RECORD - ADDRESS 1"],
    [173 , "A"  , false, 0..35 , nil, "IMPORTER OF RECORD - ADDRESS 2"],
    [174 , "A"  , false, 0..35 , nil, "IMPORTER OF RECORD - CITY"],
    [175 , "A"  , false, 0..14 , nil, "IMPORTER OF RECORD - STATE/PROVINCE"],
    [176 , "A"  , false, 0..14 , nil, "IMPORTER OF RECORD - POSTAL CODE"],
    [177 , "N"  , false, 0..9  , nil, "IMPORTER OF RECORD - ACCOUNT NUMBER"],
    [178 , "N"  , false, 0..14 , nil, "IMPORTER OF RECORD - PHONE NUMBER"],
    [179 , "N"  , false, 0..9  , nil, "IMPORTER OF RECORD - 3RD PARTY ACCOUNT NUMBER"],
    [180 , "A/N", false, 0..17 , nil, "IMPORTER OF RECORD - IRS/EIN/SSN/VAT/EORI NUMBER"],
    [181 , "A"  , false, 0..10 , nil, "IMPORTER OF RECORD - BROKER NAME"],
    [182 , "N"  , false, 0..15 , nil, "IMPORTER OF RECORD - BROKER PHONE NUMBER"],
    [183 , "N"  , false, 0..15 , nil, "SENDER PHONE NUMBER"],
    [184 , "A"  , false, 0..1  , nil, "PRE-SHIP VALIDATION FLAG"],
    [185 , "A"  , false, 0..1  , nil, "INVOICE FLAG"],
    [186 , "A/N", false, 0..1  , nil, "C.O.D. ADD FREIGHT CHARGES FLAG"],
    [187 , "A"  , false, 0..3  , nil, "LABEL FORMAT VALUE/PRINTER TYPE INDICATOR"],
    [188 , "A"  , false, 0..2  , nil, "LABEL BUFFER STRING"],
    [189 , "N"  , false, 0..11 , 2  , "GOODS AND SERVICES SALES TAX (GST)"],
    [190 , "A"  , false, 0..1  , nil, "DOCUMENT SHIPMENT FLAG"],
    [191 , "N"  , false, 0..11 , 2  , "QUEBEC SALES TAX (QST)"],
    [194 , "A"  , false, 0..3  , nil, "DELIVERY DAY"],
    [195 , "A"  , false, 0..4  , nil, "DESTINATION STATION ID"],
    [198 , "A"  , false, 0..5  , nil, "DESTINATION LOCATION ID"],
    [409 , "A/N", false, 0..7  , nil, "DELIVER BY DATE"],
    [411 , "A"  , false, 0..2  , nil, "FIELD 411"],
    [413 , "A"  , false, 0..1  , nil, "NAFTA FLAG"],
    [414 , "A"  , false, 0..3  , nil, "UNIT OF MEASURE"],
    [418 , "A"  , true , 0..74 , nil, "COMMERCIAL INVOICE (CI) COMMENT LINE"],
    [421 , "N"  , false, 0..11 , 2  , "DECLARED VALUE SURCHARGE"],
    [422 , "N"  , false, 0..11 , 2  , "OFFSHORE SURCHARGE"],
    [423 , "N"  , false, 0..11 , 2  , "OUT OF DELIVERY AREA SURCHARGE"],
    [424 , "N"  , false, 0..11 , 2  , "ALASKA SURCHARGE"],
    [425 , "N"  , false, 0..11 , 2  , "HAWAII SURCHARGE"],
    [426 , "N"  , false, 0..11 , 2  , "SATURDAY PICKUP SURCHARGE"],
    [427 , "N"  , false, 0..11 , 2  , "SATURDAY DELIVERY SURCHARGE"],
    [428 , "N"  , false, 0..11 , 2  , "DANGEROUS GOODS/HAZMAT SURCHARGE"],
    [429 , "N"  , false, 0..11 , 2  , "RESIDENTIAL SURCHARGE"],
    [430 , "N"  , false, 0..11 , 2  , "C.O.D. SURCHARGE"],
    [431 , "A"  , false, 0..1  , nil, "DIM WEIGHT USED FLAG"],
    [439 , "A"  , false, 0..35 , nil, "C.O.D. REMIT PAYOR NAME"],
    [440 , "A"  , false, 0..1  , nil, "RESIDENTIAL DELIVERY FLAG"],
    [446 , "A/N", true , 0..400, nil, "DANGEROUS GOODS TECHNICAL NAME"],
    [451 , "N"  , false, 0..4  , nil, "DANGEROUS GOODS UN NUMBER/IDENTIFICATION NUMBER"],
    [456 , "N"  , true , 0..5  , nil, "DANGEROUS GOODS NUMBER OF UNITS"],
    [461 , "A"  , true , 0..35 , nil, "DANGEROUS GOODS PACKING TYPE"],
    [466 , "N"  , true , 0..6  , 2  , "DANGEROUS GOODS/HAZMAT QUANTITY"],
    [471 , "A"  , true , 0..4  , nil, "DANGEROUS GOODS/HAZMAT UNIT OF MEASURE (UOM)"],
    [476 , "A"  , false, 0..4  , nil, "DANGEROUS GOODS PACKING INSTRUCTIONS"],
    [483 , "A"  , false, 0..200, nil, "DANGEROUS GOODS AUTHORIZATION"],
    [484 , "N"  , false, 0..25 , nil, "DANGEROUS GOODS EMERGENCY PHONE NUMBER"],
    [485 , "A"  , false, 0..35 , nil, "DANGEROUS GOODS TITLE OF SIGNATORY"],
    [486 , "A"  , false, 0..175, nil, "DANGEROUS GOODS ADDITIONAL HANDLING INFORMATION"],
    [488 , "A"  , false, 0..1  , nil, "DG CARGO AIRCRAFT ONLY FLAG"],
    [489 , "A"  , true , 0..3  , nil, "DANGEROUS GOODS/HAZMAT PACKING GROUP"],
    [492 , "A"  , false, 0..5  , nil, "DANGEROUS GOODS CLASS/DOT HAZARD CLASS OR DIVISION NUMBER"],
    [493 , "N"  , false, 0..11 , 2  , "OUTSIDE PICKUP AREA (OPA) SURCHARGE"],
    [494 , "N"  , false, 0..11 , 2  , "INSIDE PICKUP SURCHARGE AMOUNT"],
    [495 , "N"  , false, 0..11 , 2  , "INSIDE DELIVERY SURCHARGE AMOUNT"],
    [496 , "A"  , false, 0..2  , nil, "FREIGHT SERVICE COMMITMENT"],
    [497 , "N"  , false, 0..9  , nil, "MASTER METER NUMBER"],
    [498 , "N"  , false, 0..9  , nil, "METER NUMBER"],
    [499 , "N"  , false, 0..2  , nil, "TRACKING NUMBER REQUEST TYPE"],
    [526 , "N"  , false, 0..4  , nil, "TRACKING FORM ID"],
    [527 , "N"  , false, 0..4  , nil, "C.O.D. RETURN FORM ID"],
    [532 , "N"  , false, 0..9  , 2  , "COMMERCIAL INVOICE (CI) FREIGHT CHARGE"],
    [533 , "N"  , false, 0..9  , 2  , "COMMERCIAL INVOICE (CI) INSURANCE CHARGE"],
    [534 , "N"  , false, 0..9  , 2  , "COMMERCIAL INVOICE (CI) OTHER CHARGE"],
    [535 , "A"  , false, 0..32 , nil, "C.O.D. RETURN ASTRA BAR CODE"],
    [536 , "A"  , false, 0..2  , nil, "C.O.D. RETURN SERVICE COMMITMENT"],
    [537 , "A"  , false, 0..255, nil, "THERMAL PRINTER IDENTIFIER/LABEL BUFFER FILE PATH"],
    [538 , "A"  , false, 0..255, nil, "REPORT PRINTER ID"],
    [539 , "N"  , false, 0..11 , 2  , "HARMONIZED SALES TAX (HST)"],
    [540 , "N"  , false, 0..11 , 2  , "SUNDAY DELIVERY SURCHARGE"],
    [541 , "A"  , false, 0..9  , nil, "OPENSHIP FLAGS"],
    [542 , "A/N", false, 0..9  , nil, "OPENSHIP INDEX"],
    [543 , "N"  , false, 0..11 , 2  , "FREIGHT + REMIT C.O.D. CHARGES"],
    [544 , "A"  , false, 0..255, nil, "LASER PRINTER ID"],
    [545 , "A"  , false, 0..255, nil, "FORM PRINTER ID"],
    [546 , "N"  , false, 0..3  , nil, "MULTI-PLY PAPER WAYBILL FORMAT"],
    [547 , "A"  , false, 0..1  , nil, "MULTI-PLY AIR FORM PRINT FLAG"],
    [548 , "A"  , false, 0..1  , nil, "CLOSE STATUS REQUEST FLAG"],
    [549 , "A"  , false, 0..4  , nil, "CLOSE STATUS CODE"],
    [552 , "N"  , false, 0..16 , nil, "REVENUE BAR CODE"],
    [553 , "N"  , false, 0..26 , nil, "ADDRESS BAR CODE"],
    [554 , "N"  , false, 0..11 , 2  , "DELIVERY AREA SURCHARGE"],
    [556 , "N"  , false, 0..1  , nil, "PROCESS REQUEST CODE"],
    [557 , "A"  , true , 0..2  , nil, "MESSAGE TYPE CODE"],
    [558 , "A"  , true , 0..8  , nil, "MESSAGE CODE"],
    [559 , "A"  , true , 0..255, nil, "MESSAGE TEXT"],
    [560 , "A"  , false, 0..255, nil, "RATE MESSAGE TEXT"],
    [561 , "A"  , false, 0..1  , nil, "BONUS WEIGHT INDICATOR"],
    [562 , "N"  , false, 0..1  , nil, "NUMBER OF IPD/IDF LABEL COPIES - SHIPPER"],
    [563 , "N"  , false, 0..1  , nil, "NUMBER OF IPD/IDF LABEL COPIES - CUSTOMS"],
    [564 , "N"  , false, 0..1  , nil, "NUMBER OF IPD/IDF LABEL COPIES - MANIFEST"],
    [565 , "N"  , false, 0..1  , nil, "NUMBER OF IPD/IDF LABEL COPIES - RECIPIENT"],
    [566 , "N"  , false, 0..1  , nil, "NUMBER OF IPD/IDF LABEL COPIES - OVERNIGHT LETTER"],
    [567 , "A"  , false, 0..1  , nil, "DO NOT SHIP LABELS FLAG"],
    [568 , "A"  , true , 0..255, nil, "REPORT DIRECTORY"],
    [569 , "N"  , false, 0..4  , nil, "LATE DROP-OFF TIME"],
    [570 , "A"  , false, 0..255, nil, "THERMAL LABEL BUFFER DIRECTORY"],
    [571 , "A"  , false, 0..20 , nil, "THERMAL LABEL PRINTER/FORMAT TYPE"],
    [572 , "A"  , false, 0..1  , nil, "CUT FLOWERS FLAG"],
    [574 , "A/N", false, 0..2  , nil, "ORIGIN SERVICE AREA"],
    [577 , "N"  , true , 0..2  , nil, "FSMS SERVICE NAME"],
    [579 , "A"  , false, 0..1  , nil, "SEVERITY"],
    [581 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 1"],
    [582 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 2"],
    [583 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 3"],
    [584 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 4"],
    [585 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 5"],
    [586 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 6"],
    [587 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 7"],
    [588 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 8"],
    [589 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 9"],
    [590 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 10"],
    [591 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 11"],
    [592 , "A"  , false, 0..75 , nil, "CUSTOM DOC-TAB FIELD 12"],
    [601 , "A/N", false, 0..21 , nil, "ITAR LICENCE/EXEMPTION NUMBER"],
    [630 , "A/N", false, 0..1  , nil, "ITAR FLAG"],
    [650 , "A/N", true , 0..4  , nil, "OPERATIONAL ELEMENT NO. 2"],
    [651 , "A/N", true , 0..4  , nil, "OPERATIONAL ELEMENT NO. 3"],
    [652 , "A/N", true , 0..20 , nil, "OPERATIONAL ELEMENT NO. 4"],
    [653 , "A/N", true , 0..8  , nil, "OPERATIONAL ELEMENT NO. 5"],
    [654 , "A/N", true , 0..3  , nil, "OPERATIONAL ELEMENT NO. 6"],
    [655 , "A/N", true , 0..9  , nil, "OPERATIONAL ELEMENT NO. 9"],
    [656 , "A/N", true , 0..14 , nil, "OPERATIONAL ELEMENT NO. 10"],
    [657 , "A/N", true , 0..4  , nil, "OPERATIONAL ELEMENT NO. 11"],
    [658 , "A/N", true , 0..19 , nil, "OPERATIONAL ELEMENT NO. 12"],
    [659 , "A/N", true , 0..19 , nil, "OPERATIONAL ELEMENT NO. 13"],
    [660 , "A/N", true , 0..16 , nil, "OPERATIONAL ELEMENT NO. 14"],
    [661 , "A/N", true , 0..10 , nil, "OPERATIONAL ELEMENT NO. 15"],
    [662 , "A/N", true , 0..6  , nil, "OPERATIONAL ELEMENT NO. 16"],
    [663 , "A/N", true , 0..3  , nil, "OPERATIONAL ELEMENT NO. 17"],
    [664 , "N"  , true , 0..34 , nil, "FEDEX 1D BARCODE"],
    [665 , "A/N", true , 0..30 , nil, "OPERATIONAL ELEMENT NO. 8"],
    [667 , "N"  , true , 0..34 , nil, "FEDEX 1D BARCODE FOR COD"],
    [668 , "A/N", true , 0..46 , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 18"],
    [669 , "A/N", true , 0..23 , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 19"],
    [670 , "A/N", true , 0..9  , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 20"],
    [671 , "A/N", false, 0..2  , nil, "TRACKING ID TYPE"],
    [672 , "A/N", false, 0..2  , nil, "SECONDARY TRACKING ID TYPE"],
    [673 , "A/N", false, 0..2  , nil, "MASTER TRACKING ID TYPE"],
    [700 , "A/N", false, 0..4  , nil, "FIELD 700"],
    [701 , "A/N", false, 0..4  , nil, "FIELD 701"],
    [702 , "A/N", false, 0..20 , nil, "FIELD 702"],
    [703 , "A/N", false, 0..8  , nil, "FIELD 703"],
    [704 , "A/N", false, 0..3  , nil, "FIELD 704"],
    [705 , "A/N", false, 0..30 , nil, "FIELD 705"],
    [706 , "A/N", false, 0..9  , nil, "FIELD 706"],
    [707 , "A/N", false, 0..9  , nil, "FIELD 707"],
    [708 , "A/N", false, 0..14 , nil, "FIELD 708"],
    [709 , "A/N", false, 0..19 , nil, "FIELD 709"],
    [710 , "A/N", false, 0..19 , nil, "FIELD 710"],
    [711 , "A/N", false, 0..16 , nil, "FIELD 711"],
    [712 , "A/N", false, 0..10 , nil, "FIELD 712"],
    [713 , "A/N", false, 0..6  , nil, "FIELD 713"],
    [714 , "A/N", false, 0..3  , nil, "FIELD 714"],
    [715 , "A/N", false, 0..46 , nil, "FIELD 715"],
    [716 , "A/N", false, 0..23 , nil, "FIELD 716"],
    [717 , "A/N", false, 0..9  , nil, "FIELD 717"],
    [1000, "A"  , false, 0..8  , nil, "COMPONENT VERSION"],
    [1008, "N"  , false, 0..6  , nil, "PACKAGE READY TIME"],
    [1011, "N"  , false, 0..20 , nil, "FIELD 1011"],
    [1023, "A"  , false, 0..100, nil, "GMT TIME ZONE"],
    [1030, "N"  , true , 0..15 , 6  , "COMMODITY LINE ITEM UNIT VALUE"],
    [1032, "A"  , false, 0..2  , nil, "DUTY PAYOR COUNTRY CODE"],
    [1053, "A"  , false, 0..26 , nil, "DOWNLOAD FLAG"],
    [1063, "A"  , false, 0..1  , nil, "INTERNATIONAL SHIPMENT FLAG"],
    [1064, "A"  , false, 0..1  , nil, "DOMESTIC SHIPMENT FLAG"],
    [1084, "A/N", false, 0..5  , nil, "ORIGIN STATION ID"],
    [1086, "N"  , true , 0..9  , 1  , "DIM WEIGHT"],
    [1087, "N"  , false, 0..9  , 2  , "FIELD 1087"],
    [1089, "N"  , false, 0..5  , nil, "RATE SCALE"],
    [1090, "A"  , false, 0..3  , nil, "DECLARED VALUE/RATE CURRENCY TYPE"],
    [1092, "N"  , true , 0..2  , nil, "RATE ZONE"],
    [1097, "A"  , false, 0..1  , nil, "NOT IN FREE CIRCULATION"],
    [1100, "A"  , false, 0..1  , nil, "ODA FLAG"],
    [1103, "N"  , false, 0..15 , nil, "SENDER FAX NUMBER"],
    [1115, "N"  , false, 0..6  , nil, "SHIP TIME"],
    [1116, "A"  , false, 0..1  , nil, "DIM UNITS"],
    [1117, "N"  , false, 0..4  , nil, "PACKAGE SEQUENCE"],
    [1118, "N"  , false, 0..10 , nil, "RELEASE AUTHORIZATION NUMBER"],
    [1119, "A"  , false, 0..1  , nil, "FUTURE DAY FLAG"],
    [1120, "A"  , false, 0..1  , nil, "INSIDE PICKUP FLAG"],
    [1121, "A"  , false, 0..1  , nil, "INSIDE DELIVERY FLAG"],
    [1123, "N"  , false, 0..20 , nil, "MASTER TRACKING NUMBER"],
    [1124, "N"  , false, 0..4  , nil, "MASTER FORM ID"],
    [1125, "N"  , false, 0..4  , nil, "RATE RETURN CODE"],
    [1133, "N"  , false, 0..2  , nil, "FIELD 1133"],
    [1136, "A"  , false, 0..2  , nil, "URSA PREFIX"],
    [1139, "N"  , false, 0..18 , nil, "SENDER IRS/EIN/EORI NUMBER"],
    [1145, "A"  , false, 0..12 , nil, "RECIPIENT DEPARTMENT NAME"],
    [1148, "A"  , false, 0..4  , nil, "FEDEX MIDDLEWARE PRODUCT NAME"],
    [1149, "A"  , false, 0..4  , nil, "FEDEX MIDDLEWARE PRODUCT VERSION"],
    [1151, "N"  , false, 0..1  , nil, "ORIGIN INDICATOR"],
    [1153, "A"  , false, 0..1  , nil, "METER INDICATOR"],
    [1154, "A"  , false, 0..20 , nil, "ACU STATUS"],
    [1155, "N"  , false, 0..27 , nil, "ACU STATUS FLAG"],
    [1156, "N"  , false, 0..2  , nil, "PERIPHERAL INDICATOR"],
    [1174, "A"  , false, 0..1  , nil, "BSO FLAG"],
    [1176, "A"  , false, 0..1  , nil, "DELETED SHIPMENT FLAG"],
    [1178, "A"  , false, 0..6  , nil, "URSA SUFFIX"],
    [1179, "N"  , false, 0..10 , nil, "BROKER ACCOUNT NUMBER"],
    [1180, "A"  , false, 0..35 , nil, "BROKER COMPANY"],
    [1181, "A"  , false, 0..35 , nil, "BROKER ADDRESS LINE 1"],
    [1182, "A"  , false, 0..35 , nil, "BROKER ADDRESS LINE 2"],
    [1183, "A"  , false, 0..35 , nil, "BROKER CITY"],
    [1184, "A"  , false, 0..14 , nil, "BROKER STATE/PROVINCE"],
    [1185, "A"  , false, 0..10 , nil, "BROKER POSTAL CODE"],
    [1186, "A"  , false, 0..2  , nil, "BROKER COUNTRY CODE"],
    [1187, "A"  , false, 0..15 , nil, "BROKER ID"],
    [1194, "N"  , false, 0..3  , nil, "COMMERCIAL INVOICE TRANSACTION COUNT"],
    [1195, "A"  , false, 0..2  , nil, "BILL TO COUNTRY CODE"],
    [1200, "A"  , false, 0..1  , nil, "HOLD AT LOCATION FLAG"],
    [1201, "A/N", false, 0..120, nil, "SENDER'S EMAIL ADDRESS"],
    [1202, "A/N", false, 0..120, nil, "RECIPIENT'S EMAIL ADDRESS"],
    [1203, "A"  , false, 0..120, nil, "PERSONAL MESSAGE"],
    [1204, "A/N", true , 0..120, nil, "SHIP ALERT EMAIL ADDRESS"],
    [1206, "A"  , true , 0..1  , nil, "OTHER SHIPALERT NOTIFICATION FLAG"],
    [1208, "A"  , false, 0..1  , nil, "SIGNATURE REQUIRED FLAG"],
    [1209, "A"  , false, 0..1  , nil, "PRIORITY ALERT FLAG"],
    [1211, "A"  , false, 0..35 , nil, "POD ADDRESS"],
    [1221, "A"  , false, 0..1  , nil, "USE PRESET TRACKING NUMBER FLAG"],
    [1222, "N"  , false, 0..20 , nil, "PRESET TRACKING NUMBER"],
    [1223, "N"  , true , 0..4  , nil, "PREASSIGNED FORM ID"],
    [1224, "N"  , false, 0..15 , nil, "PREASSIGNED C.O.D. RETURN TRACKING NUMBER"],
    [1225, "N"  , false, 0..4  , nil, "PREASSIGNED C.O.D. RETURN FORM ID"],
    [1234, "N"  , false, 0..1  , nil, "RATE/ROUTE/TIME-IN-TRANSIT FLAG"],
    [1237, "N"  , false, 0..15 , nil, "C.O.D. RETURN PHONE NUMBER"],
    [1238, "A"  , false, 0..35 , nil, "C.O.D. RETURN COMPANY NAME"],
    [1239, "A"  , false, 0..12 , nil, "C.O.D. RETURN DEPARTMENT"],
    [1240, "A"  , false, 0..35 , nil, "C.O.D. RETURN ADDRESS LINE 1"],
    [1241, "A"  , false, 0..35 , nil, "C.O.D. RETURN ADDRESS LINE 2"],
    [1242, "A"  , false, 0..35 , nil, "C.O.D. RETURN CITY"],
    [1243, "A"  , false, 0..2  , nil, "C.O.D. RETURN STATE"],
    [1244, "A"  , false, 0..10 , nil, "C.O.D. RETURN POSTAL CODE"],
    [1248, "A"  , false, 0..1  , nil, "SUNDAY DELIVERY FLAG"],
    [1266, "A"  , false, 0..1  , nil, "SATURDAY DELIVERY FLAG"],
    [1267, "A"  , false, 0..1  , nil, "SATURDAY PICKUP FLAG"],
    [1268, "A"  , false, 0..1  , nil, "DRY ICE FLAG"],
    [1271, "N"  , false, 0..5  , nil, "SHIPPER'S LOAD AND COUNT (SLAC)/NUMBER OF PALLETS"],
    [1272, "N"  , false, 0..12 , nil, "BOOKING NUMBER"],
    [1273, "N"  , false, 0..2  , nil, "PACKAGING TYPE"],
    [1274, "A/N", false, 0..3  , nil, "SERVICE TYPE"],
    [1275, "A"  , false, 0..20 , nil, "COMMODITY LINE ITEM PART NUMBER"],
    [1277, "N"  , false, 0..6  , nil, "RECIPIENT TELEPHONE EXTENSION"],
    [1282, "A"  , false, 0..1  , nil, "PRINTER TYPE INDICATOR"],
    [1297, "A/N", false, 0..15 , nil, "CUSTOMER INVOICE NUMBER"],
    [1298, "N"  , false, 0..6  , nil, "SENDER PHONE EXTENSION"],
    [1300, "A"  , false, 0..15 , nil, "PURCHASE ORDER NUMBER"],
    [1311, "N"  , false, 0..1  , nil, "NUMBER OF LABEL COPIES - SHIPPER"],
    [1312, "N"  , false, 0..1  , nil, "NUMBER OF LABEL COPIES - CUSTOMS"],
    [1313, "N"  , false, 0..1  , nil, "NUMBER OF LABEL COPIES - MANIFEST"],
    [1324, "A"  , false, 0..36 , nil, "RECIPIENT COUNTRY DESCRIPTION"],
    [1331, "A"  , true , 0..1  , nil, "DANGEROUS GOODS/HAZMAT FLAG"],
    [1332, "A"  , false, 0..1  , nil, "ALCOHOL FLAG"],
    [1333, "A"  , false, 0..1  , nil, "DROP OFF FLAG"],
    [1337, "A"  , false, 0..40 , nil, "PACKAGE CONTENT INFORMATION"],
    [1338, "N"  , false, 0..11 , 2  , "PRIORITY ALERT SURCHARGE"],
    [1341, "A"  , false, 0..15 , nil, "SENDER PAGER NUMBER"],
    [1342, "A"  , false, 0..15 , nil, "RECIPIENT PAGER NUMBER"],
    [1343, "A/N", false, 0..120, nil, "BROKER EMAIL ADDRESS"],
    [1344, "N"  , false, 0..15 , nil, "BROKER FAX NUMBER"],
    [1345, "N"  , false, 0..15 , nil, "BROKER PAGER NUMBER"],
    [1349, "A"  , false, 0..1  , nil, "AES FILING STATUS"],
    [1352, "A"  , false, 0..1  , nil, "SENDER IDENTIFICATION TYPE"],
    [1353, "A"  , false, 0..1  , nil, "INTERMEDIATE CONSIGNEE"],
    [1354, "A"  , false, 0..15 , nil, "PACKING SLIP NUMBER"],
    [1355, "A/N", false, 0..15 , nil, "CONSOLIDATED INDEX"],
    [1357, "N"  , false, 0..2  , nil, "MISCELLANEOUS CHARGES"],
    [1358, "A"  , false, 0..32 , nil, "FTR, XTN, OR ITN ENTRY"],
    [1359, "A"  , false, 0..32 , nil, "SED/EEI LEGEND NUMBER"],
    [1361, "A"  , false, 0..1  , nil, "SHIPMENT STATUS"],
    [1370, "N"  , false, 0..1  , nil, "DOC-TAB ORIENTATION -"],
    [1373, "N"  , false, 0..3  , nil, "REPORT CODE"],
    [1374, "A"  , false, 0..1  , nil, "PRINT ON CONSIGNEE LABELS FLAG"],
    [1375, "N"  , true , 0..1  , nil, "LABEL STOCK ORIENTATION"],
    [1380, "N"  , false, 0..8  , nil, "COMPONENT START DATE"],
    [1381, "N"  , false, 0..8  , nil, "COMPONENT END DATE"],
    [1382, "N"  , false, 0..1  , nil, "COMPONENT STATUS"],
    [1387, "N"  , false, 0..4  , nil, "DATABASE BACKUP TIME"],
    [1392, "N"  , false, 0..1  , nil, "BLOCK SHIPMENT DATA"],
    [1393, "N"  , false, 0..11 , 2  , "FUEL SURCHARGE AMOUNT"],
    [1398, "A/N", true , 0..80 , nil, "FIELD 1398"],
    [1399, "A"  , false, 0..15 , nil, "AES ENTRY NUMBER"],
    [1455, "A"  , false, 0..1  , nil, "CUSTOMS VALUE MASK"],
    [1483, "A"  , false, 0..4  , nil, "STANDARD CARRIER ALPHANUMERIC CODE (SCAC)"],
    [1484, "A"  , false, 0..1  , nil, "LINEHAUL FLAG"],
    [1485, "A"  , false, 0..35 , nil, "RETURN ADDRESS CONTACT NAME"],
    [1486, "A"  , false, 0..35 , nil, "RETURN ADDRESS COMPANY NAME"],
    [1487, "A"  , false, 0..35 , nil, "RETURN ADDRESS LINE 1"],
    [1488, "A"  , false, 0..35 , nil, "RETURN ADDRESS LINE 2"],
    [1489, "A"  , false, 0..35 , nil, "RETURN ADDRESS CITY"],
    [1490, "A"  , false, 0..2  , nil, "RETURN ADDRESS STATE/PROVINCE"],
    [1491, "A/N", false, 0..10 , nil, "RETURN ADDRESS POSTAL CODE"],
    [1492, "N"  , false, 0..15 , nil, "RETURN ADDRESS PHONE NUMBER"],
    [1493, "A"  , false, 0..1  , nil, "DG/HAZMAT FORM PRINT FLAG"],
    [1498, "N"  , false, 0..1  , nil, "FEDEX LINEHAUL PAYMENT TYPE"],
    [1500, "N"  , false, 0..9  , nil, "FEDEX LINEHAUL ACCOUNT NUMBER"],
    [1502, "N"  , false, 0..9  , nil, "FEDEX TRADE NETWORKS BROKER OPTION"],
    [1503, "N"  , false, 0..9  , nil, "FEDEX TRADE NETWORKS BROKER DTF ACCOUNT NUMBER"],
    [1507, "N"  , false, 0..11 , 2  , "LIST TOTAL SURCHARGE"],
    [1508, "N"  , false, 0..11 , 2  , "LIST SHIPMENT NOTIFY SURCHARGE"],
    [1509, "N"  , false, 0..11 , 2  , "LIST SATURDAY DELIVERY SURCHARGE"],
    [1510, "N"  , false, 0..11 , 2  , "LIST RESIDENTIAL SURCHARGE"],
    [1511, "N"  , true , 0..4  , nil, "LIST RATE RETURN CODE"],
    [1512, "N"  , false, 0..11 , 2  , "LIST PRIORITY ALERT SURCHARGE"],
    [1513, "N"  , false, 0..11 , 2  , "LIST SATURDAY PICKUP SURCHARGE"],
    [1514, "N"  , false, 0..11 , 2  , "LIST INSIDE PICKUP SURCHARGE"],
    [1515, "N"  , false, 0..11 , 2  , "LIST INSIDE DELIVERY SURCHARGE"],
    [1516, "N"  , false, 0..11 , 2  , "LIST C.O.D. SURCHARGE"],
    [1517, "N"  , false, 0..11 , 2  , "LIST OUTSIDE PICKUP AREA SURCHARGE"],
    [1518, "N"  , false, 0..11 , 2  , "LIST OUTSIDE DELIVERY AREA SURCHARGE"],
    [1519, "N"  , false, 0..11 , 2  , "LIST BASE CHARGE"],
    [1520, "N"  , false, 0..11 , 2  , "LIST FUEL SURCHARGE"],
    [1521, "N"  , false, 0..11 , 2  , "LIST ALASKA SURCHARGE"],
    [1522, "N"  , false, 0..11 , 2  , "LIST DELIVERY AREA SURCHARGE"],
    [1523, "N"  , false, 0..11 , 2  , "LIST DECLARED VALUE CHARGE"],
    [1524, "N"  , false, 0..11 , 2  , "LIST HAWAII SURCHARGE"],
    [1525, "N"  , true , 0..11 , 2  , "EFFECTIVE NET DISCOUNT"],
    [1526, "N"  , false, 0..11 , 2  , "LIST DANGEROUS GOODS/HAZMAT SURCHARGE"],
    [1528, "N"  , false, 0..11 , 2  , "LIST NET CHARGE AMOUNT"],
    [1533, "N"  , false, 0..11 , 2  , "NET FREIGHT CHARGE BEFORE CANADA TAXES"],
    [1539, "N"  , false, 0..15 , nil, "TD 3RD PARTY BROKER DTF ZIP/POSTAL CODE"],
    [1540, "A"  , false, 0..35 , nil, "3RD PARTY BROKER DTF PAYOR - CONTACT NAME"],
    [1541, "A"  , false, 0..35 , nil, "3RD PARTY BROKER DTF PAYOR - ADDRESS LINE 1"],
    [1542, "A"  , false, 0..35 , nil, "3RD PARTY BROKER DTF PAYOR - CITY"],
    [1543, "A"  , false, 0..35 , nil, "3RD PARTY BROKER DTF PAYOR - STATE/PROVINCE"],
    [1544, "A"  , false, 0..2  , nil, "3RD PARTY BROKER DTF PAYOR - COUNTRY"],
    [1545, "N"  , false, 0..15 , nil, "3RD PARTY BROKER DTF PAYOR - PHONE NUMBER"],
    [1546, "N"  , false, 0..1  , nil, "FEDEX TRADE NETWORKS BROKER DTF PAYMENT TYPE"],
    [1547, "N"  , false, 0..9  , nil, "APD/PCV ACCOUNT NUMBER"],
    [1548, "N"  , false, 0..1  , nil, "APD/PCV PAYMENT TYPES"],
    [1550, "A"  , false, 0..1  , nil, "PIECE COUNT VERIFICATION (PCV) FLAG"],
    [1551, "A"  , false, 0..1  , nil, "DELIVERY NOTIFY FLAG"],
    [1552, "A"  , true , 0..2  , nil, "OTHER LANGUAGE CODE"],
    [1553, "N"  , false, 0..11 , 2  , "SHIPPER DELIVERY NOTIFICATION FLAG (POD)"],
    [1554, "A"  , false, 0..1  , nil, "SHIPPER SHIPALERT FLAG"],
    [1555, "A"  , false, 0..2  , nil, "SHIPPER LANGUAGE CODE"],
    [1556, "A"  , false, 0..1  , nil, "RECIPIENT DELIVERY NOTIFICATION FLAG (POD)"],
    [1557, "A"  , false, 0..1  , nil, "RECIPIENT SHIPALERT FLAG"],
    [1558, "A"  , false, 0..2  , nil, "RECIPIENT LANGUAGE CODE"],
    [1559, "A"  , false, 0..1  , nil, "BROKER DELIVERY NOTIFICATION FLAG (POD)"],
    [1560, "A"  , false, 0..1  , nil, "BROKER SHIPALERT FLAG"],
    [1561, "A"  , false, 0..2  , nil, "BROKER LANGUAGE CODE"],
    [1582, "N"  , false, 0..8  , nil, "BEGIN DATE"],
    [1583, "N"  , false, 0..8  , nil, "END DATE"],
    [1585, "N"  , false, 0..2  , nil, "RETURN COUNTRY CODE"],
    [1586, "A"  , false, 0..1  , nil, "PRINT ALTERNATE RETURN ADDRESS FLAG"],
    [1588, "N"  , true , 0..1  , nil, "HANDLING CHARGE TYPE"],
    [1590, "N"  , false, 0..3  , nil, "ACU SOLUTION TYPE"],
    [1591, "N"  , false, 0..2  , nil, "ACU INDICATOR"],
    [1592, "A"  , false, 0..1  , nil, "SHIPMENT LEVEL INDICATOR"],
    [1593, "A"  , false, 0..1  , nil, "ACCUMULATE SHIPMENT CHARGES INDICATOR"],
    [1595, "N"  , true , 0..7  , 2  , "HANDLING CHARGE AMOUNT OR PERCENTAGE"],
    [1596, "N"  , true , 0..11 , 2  , "HANDLING CHARGE"],
    [1597, "N"  , false, 0..11 , 2  , "LIST HANDLING CHARGE"],
    [1598, "N"  , true , 0..11 , 2  , "TOTAL CUSTOMER HANDLING CHARGE"],
    [1599, "N"  , true , 0..11 , 2  , "LIST TOTAL CUSTOMER HANDLING CHARGE"],
    [1606, "N"  , true , 0..1  , nil, "HANDLING CHARGE APPLICATION POINT"],
    [1619, "A"  , true , 0..5  , nil, "DOC-TAB TYPE"],
    [1621, "A/N", false, 0..30 , nil, "CUSTOM DOCTAB BARCODE DATA"],
    [1622, "N"  , false, 0..4  , nil, "INTERNATIONAL DOC-TAB VALUES"],
    [1646, "A"  , false, 0..1  , nil, "SATURDAY PICKUP FLAG"],
    [1651, "N"  , false, 0..1  , nil, "B13A FILING OPTIONS"],
    [1652, "A"  , false, 0..50 , nil, "EXPORT STATEMENT DATA"],
    [1653, "A"  , false, 0..10 , nil, "EXPORT PERMIT NUMBER"],
    [1654, "A"  , false, 0..1  , nil, "IPD/IED FLAG"],
    [1658, "A"  , false, 0..5  , nil, "TD U.S. DROP-OFF LOCATION - LODID"],
    [1659, "A"  , false, 0..35 , nil, "TD U.S. DROP-OFF LOCATION - ADDRESS 1"],
    [1660, "A"  , false, 0..1  , nil, "CUSTOM LABEL FLAG"],
    [1662, "A"  , false, 0..35 , nil, "TD U.S. DROP-OFF LOCATION - CITY"],
    [1663, "A"  , false, 0..2  , nil, "TD U.S. DROP-OFF LOCATION - STATE"],
    [1664, "N"  , false, 0..15 , nil, "TD U.S. DROP-OFF LOCATION - POSTAL CODE"],
    [1666, "A"  , false, 0..35 , nil, "FIELD 1666"],
    [1669, "A"  , false, 0..1  , nil, "EXCEPTED QUANTITIES FLAG"],
    [1670, "N"  , true , 0..8  , 2  , "PACKAGE WEIGHT/SHIPMENT WEIGHT"],
    [1674, "N"  , false, 0..2  , nil, "DG IATA SEQUENCE NUMBER"],
    [1677, "N"  , false, 0..1  , nil, "COMMODITY ACTION CODE"],
    [1678, "A/N", false, 0..9  , nil, "COMMODITY INDEX NUMBER"],
    [1679, "A"  , false, 0..255, nil, "DG PRINTER ID"],
    [1680, "N"  , false, 0..2  , nil, "DG PRINTER FORM TYPE"],
    [1682, "N"  , false, 0..11 , 2  , "OVERSIZE SURCHARGE"],
    [1683, "N"  , false, 0..11 , 2  , "LIST OVERSIZE SURCHARGE"],
    [1684, "N"  , true , 0..10 , 2  , "DRY ICE WEIGHT"],
    [1686, "A"  , false, 0..1  , nil, "SHIPMENT DIMENSIONAL INDICATOR"],
    [1687, "A"  , false, 0..1  , nil, "IDF FLAG"],
    [1688, "N"  , false, 0..2  , nil, "NUMBER OF REPORT COPIES"],
    [1689, "A"  , false, 0..3  , nil, "SHIPMENT QUERY CODE"],
    [1690, "A"  , false, 0..1  , nil, "SATURDAY DELIVERY FLAG"],
    [1757, "N"  , false, 0..11 , 2  , "LIST INTRA COUNTRY TAX"],
    [1758, "N"  , false, 0..11 , 2  , "INTRA COUNTRY TAX"],
    [1795, "N"  , false, 0..11 , 2  , "HOLD AT LOCATION SURCHARGE"],
    [1796, "N"  , false, 0..11 , 2  , "LIST HOLD AT LOCATION SURCHARGE"],
    [1797, "N"  , false, 0..11 , 2  , "ALTERNATE HOLD AT LOCATION SURCHARGE"],
    [1798, "N"  , false, 0..1  , nil, "REFERENCE DESIGNATION FOR CLOSE"],
    [1799, "A"  , false, 0..1  , nil, "NAFTA ROLES"],
    [1803, "N"  , false, 0..1  , nil, "OPENSHIP VERIFICATION ERROR OPTIONS"],
    [1804, "N"  , false, 0..1  , nil, "REPORT PRINT/GENERATION OPTIONS"],
    [1850, "A"  , true , 0..1  , nil, "PRIORITY ALERT PLUS FLAG"],
    [1851, "N"  , true , 0..11 , 2  , "PRIORITY ALERT PLUS SURCHARGE"],
    [1852, "N"  , true , 0..11 , 2  , "LIST PRIORITY ALERT PLUS SURCHARGE"],
    [1853, "N"  , true , 0..11 , 2  , "ALTERNATE PRIORITY ALERT PLUS SURCHARGE"],
    [1867, "A"  , false, 0..3  , nil, "ENABLE IATA DG VALIDATION FLAGS"],
    [1870, "N"  , false, 0..1  , nil, "NET EXPLOSIVE MASS TYPE"],
    [1871, "A"  , false, 0..2  , nil, "NET EXPLOSIVE MASS UNIT OF MEASURE"],
    [1872, "N"  , false, 0..12 , 5  , "NET EXPLOSIVE MASS AMOUNT"],
    [1902, "A/N", false, 0..9  , nil, "SUBSIDIARY RISK"],
    [1903, "A/N", false, 0..200, nil, "DEPARTMENT OF TRANSPORTATION (DOT) SHIPPING NAME OF MATERIAL"],
    [1904, "A"  , false, 0..1  , nil, "DANGEROUS GOODS A1, A2, A51, A109 FLAG"],
    [1905, "A"  , false, 0..35 , nil, "DANGEROUS GOODS RADIO NUCLIDE"],
    [1906, "N"  , false, 0..10 , 5  , "DANGEROUS GOODS ACTIVITY"],
    [1907, "A"  , false, 0..3  , nil, "DANGEROUS GOODS ACTIVITY MEASUREMENT"],
    [1908, "A"  , false, 0..14 , nil, "DANGEROUS GOODS RADIOACTIVE PACKAGING TYPE"],
    [1909, "N"  , false, 0..4  , 1  , "DANGEROUS GOODS TRANSPORT INDEX"],
    [1910, "A"  , true , 0..2  , nil, "DANGEROUS GOODS RADIOACTIVE LABEL TYPE"],
    [1911, "N"  , true , 0..6  , nil, "DANGEROUS GOODS SURFACE READING"],
    [1912, "N"  , true , 0..3  , nil, "DANGEROUS GOODS PACKAGE DIM LENGTH"],
    [1913, "N"  , true , 0..3  , nil, "DANGEROUS GOODS PACKAGE DIM WIDTH"],
    [1914, "N"  , true , 0..3  , nil, "DANGEROUS GOODS PACKAGE DIM HEIGHT"],
    [1915, "A"  , true , 0..4  , nil, "DANGEROUS GOODS DIM UNITS"],
    [1916, "A"  , true , 0..7  , nil, "DANGEROUS GOODS PHYSICAL FORM"],
    [1917, "A"  , true , 0..200, nil, "DANGEROUS GOODS CHEMICAL FORMULA"],
    [1918, "A"  , false, 0..35 , nil, "DANGEROUS GOODS NAME OF SIGNATORY"],
    [1919, "N"  , false, 0..2  , nil, "DANGEROUS GOODS PERCENTAGE NUMBER"],
    [1920, "A"  , false, 0..50 , nil, "DANGEROUS GOODS RESPONSIBLE PARTY"],
    [1921, "N"  , false, 0..25 , nil, "DANGEROUS GOODS INFECTIOUS SUBSTANCE TELEPHONE NUMBER"],
    [1922, "A"  , false, 0..35 , nil, "DANGEROUS GOODS PLACE OF SIGNATORY"],
    [1923, "A"  , false, 0..1  , nil, "DANGEROUS GOODS ALL PACKED IN ONE FLAG"],
    [1924, "A"  , false, 0..1  , nil, "DANGEROUS GOODS OVERPACK FLAG"],
    [1925, "N"  , false, 0..2  , nil, "DANGEROUS GOODS NUMBER OF OVERPACKS"],
    [1926, "A"  , false, 0..1  , nil, "DANGEROUS GOODS CONSIGNMENT OF OVERPACKS FLAG"],
    [1927, "A"  , false, 0..100, nil, "DANGEROUS GOODS PACKING TYPE OF OUTER CONTAINER"],
    [1928, "A"  , false, 0..1  , nil, "DANGEROUS GOODS CONSIGNMENT OF ALL PACKED IN ONE FLAG"],
    [1929, "N"  , false, 0..3  , nil, "DANGEROUS GOODS ALL PACKED IN ONE QUANTITY"],
    [1930, "N"  , false, 0..9  , nil, "Q-VALUE"],
    [1931, "A"  , false, 0..1  , nil, "DANGEROUS GOODS A81 INDICATOR"],
    [1932, "N"  , false, 0..1  , nil, "DANGEROUS GOODS COMMODITY COUNT"],
    [1933, "A"  , false, 0..2  , nil, "COMMERCIAL INVOICE (CI) LANGUAGE CODE"],
    [1934, "N"  , false, 0..1  , nil, "CUSTOMS DOCUMENTATION REQUIREMENTS  "],
    [1935, "A"  , false, 0..1  , nil, "REPRINT TYPE"],
    [1936, "N"  , false, 0..11 , 2  , "LIST GOODS AND SERVICES SALES TAX (GST)"],
    [1937, "N"  , false, 0..11 , 2  , "LIST HARMONIZED SALES TAX (HST)"],
    [1938, "N"  , false, 0..11 , 2  , "LIST QUEBEC SALES TAX (QST)"],
    [1939, "N"  , false, 0..10 , nil, "FIELD 1939"],
    [1940, "N"  , false, 0..1  , nil, "EXCEPTED PACKAGES RADIOACTIVE MATERIALS INDICATOR"],
    [1942, "A"  , false, 0..1  , nil, "CARTAGE DELIVERY FLAG"],
    [1943, "A"  , false, 0..1  , nil, "USPS DELIVERY FLAG"],
    [1944, "A"  , false, 0..1  , nil, "ALTERNATE DAY SERVICE DELIVERY FLAG"],
    [1945, "N"  , true , 0..5  , nil, "LIST DYNAMIC SURCHARGE CODE AND/OR FEES CODE"],
    [1946, "N"  , true , 0..11 , 2  , "LIST SURCHARGE VALUE"],
    [1947, "N"  , true , 0..5  , nil, "DYNAMIC SURCHARGE AND/OR FEES CODE"],
    [1948, "N"  , true , 0..11 , 2  , "SURCHARGE VALUE"],
    [1949, "A"  , false, 0..3  , nil, "TRANSPORTATION PAY TYPE"],
    [1950, "A"  , false, 0..3  , nil, "DUTY/TAX PAY TYPE"],
    [1951, "A"  , false, 0..1  , nil, "POSTAL AWARE COUNTRY"],
    [1952, "A"  , false, 0..1  , nil, "SED/EEI REQUIRED COUNTRY"],
    [1953, "N"  , false, 0..1  , nil, "MINIMUM DCV"],
    [1954, "A"  , false, 0..1  , nil, "SHIP TO COUNTRY FLAG"],
    [1955, "A"  , false, 0..1  , nil, "COUNTRY ALIAS FLAG"],
    [1958, "A"  , false, 0..3  , nil, "ADMISSIBILITY PACKAGE TYPE"],
    [1959, "A"  , false, 0..20 , nil, "DOC-TAB HEADER"],
    [1960, "A"  , false, 0..1  , nil, "OTHER EXCEPTION NOTIFICATION FLAG"],
    [1961, "A"  , false, 0..1  , nil, "SHIPPER EXCEPTION NOTIFICATION FLAG"],
    [1962, "A"  , false, 0..1  , nil, "RECIPIENT EXCEPTION NOTIFICATION FLAG"],
    [1963, "A"  , false, 0..1  , nil, "BROKER EXCEPTION NOTIFICATION FLAG"],
    [1964, "A"  , false, 0..1  , nil, "OTHER EMAIL NOTIFICATION FORMAT TYPE"],
    [1965, "A"  , false, 0..1  , nil, "SHIPPER NOTIFICATION FORMAT"],
    [1966, "A"  , false, 0..1  , nil, "RECIPIENT NOTIFICATION FORMAT TYPE"],
    [1967, "A"  , false, 0..1  , nil, "BROKER NOTIFICATION FORMAT TYPE"],
    [1968, "A"  , false, 0..2  , nil, "OTHER LANGUAGE LOCALE CODE"],
    [1969, "A"  , false, 0..2  , nil, "SHIPPER LOCALE CODE"],
    [1970, "A"  , false, 0..2  , nil, "RECIPIENT LOCALE CODE"],
    [1971, "A"  , false, 0..2  , nil, "BROKER LOCALE CODE"],
    [1975, "N"  , false, 0..11 , 2  , "FIELD 1975"],
    [1980, "A"  , false, 0..256, nil, "XML NON-SHIPPING LABEL"],
    [1981, "A"  , true , 0..10 , nil, "PUBLISHED DELIVERY TIME"],
    [1982, "N"  , false, 0..4  , nil, "MPS TOTAL PACKAGES"],
    [1986, "A/N", false, 0..1  , nil, "NON-RESIDENT IMPORTER"],
    [1987, "A"  , false, 0..35 , nil, "SERVICE SHORT NAME"],
    [1988, "A"  , false, 0..60 , nil, "SERVICE BRANDED NAME"],
    [1989, "N"  , false, 0..2  , nil, "TRANSACTION FUNCTION"],
    [1990, "A"  , true , 0..75 , nil, "SPECIAL SERVICE ACCESSORIAL NAME"],
    [1991, "A"  , true , 0..20 , nil, "PACKAGING BRANDED NAME"],
    [1992, "N"  , false, 0..13 , 2  , "EARNED DISCOUNT AMOUNT"],
    [1993, "A"  , true , 0..1  , nil, "SHIPPING TYPE"],
    [1997, "N"  , true , 0..1  , nil, "CONTRACTUAL SERVICE INDICATOR"],
    [1998, "N"  , false, 0..50 , nil, "FIELD 1998"],
    [1854, "A"  , false, 0..1  , nil, "PHARMACY DELIVERY INDICATOR"],
    [2028, "A"  , false, 0..1  , nil, "NO SHIPTIME RATES"],
    [2152, "A/N", false, 0..2  , nil, "NAFTA CERTIFICATE OF ORIGIN - PREFERENCE CRITERION"],
    [2153, "N"  , false, 0..1  , nil, "NAFTA CERTIFICATE OF ORIGIN - COMMODITY PRODUCER"],
    [2154, "N"  , false, 0..1  , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER STATE CODE"],
    [2155, "N"  , false, 0..8  , nil, "NAFTA CERTIFICATE OF ORIGIN - NET COST BEGIN DATE"],
    [2156, "N"  , false, 0..8  , nil, "NAFTA CERTIFICATE OF ORIGIN - NET COST END DATE"],
    [2157, "A"  , false, 0..2  , nil, "NAFTA CERTIFICATE OF ORIGIN - COUNTRY OF ORIGIN"],
    [2158, "N"  , false, 0..1  , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER"],
    [2159, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER COMPANY NAME"],
    [2160, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER CONTACT NAME"],
    [2161, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER ADDRESS LINE 1"],
    [2162, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER ADDRESS LINE 2"],
    [2163, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER CITY"],
    [2164, "A"  , false, 0..2  , nil, "FIELD 2164"],
    [2165, "A/N", false, 0..15 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER POSTAL CODE"],
    [2166, "A"  , false, 0..2  , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER COUNTRY CODE"],
    [2167, "A/N", false, 0..15 , nil, "NAFTA CERTIFICATE OF ORIGIN - PRODUCER TAX ID/EIN"],
    [2168, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - COMPANY"],
    [2169, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - NAME"],
    [2170, "AKE", false, 0..35 , nil, "NAFTA CERTIFICATE OF ORIGIN - TITLE"],
    [2171, "AKE", false, 0..15 , nil, "NAFTA CERTIFICATE OF ORIGIN - TELEPHONE NUMBER"],
    [2172, "AKE", false, 0..15 , nil, "NAFTA CERTIFICATE OF ORIGIN - FAX NUMBER"],
    [2210, "A"  , false, 0..20 , nil, "RMA NUMBER"],
    [2238, "N"  , false, 0..8  , nil, "FIELD 2238"],
    [2254, "N"  , false, 0..15 , nil, "FIELD 2254"],
    [2382, "N"  , false, 0..1  , nil, "RETURN SHIPMENT INDICATOR"],
    [2387, "N"  , false, 0..8  , nil, "EMAIL LABEL EXPIRATION DATE"],
    [2388, "A/N", false, 0..200, nil, "RETURNING PARTY EMAIL MESSAGE"],
    [2389, "N"  , false, 0..10 , nil, "MERCHANT CONTACT PHONE NUMBER"],
    [2392, "A/N", false, 0..120, nil, "RETURNING PARTY EMAIL ADDRESS"],
    [2393, "A"  , false, 0..120, nil, "FIELD 2393"],
    [2394, "N"  , false, 0..15 , nil, "FIELD 2394"],
    [2395, "N"  , false, 0..11 , 2  , "TPC SURCHARGE"],
    [2396, "N"  , false, 0..2  , nil, "DOCUMENT DESCRIPTION"],
    [2397, "N"  , false, 0..2  , nil, "PURPOSE OF SHIPMENT CODE"],
    [2398, "N"  , false, 0..3  , 2  , "CI COMPANY LETTERHEAD HEADER"],
    [2399, "N"  , true , 0..1  , nil, "SIGNATURE REQUIRED TYPE"],
    [2400, "N"  , false, 0..11 , 2  , "SIGNATURE OPTION FEE"],
    [2401, "N"  , false, 0..11 , 2  , "LIST SIGNATURE OPTION FEE"],
    [2404, "A"  , false, 0..5  , nil, "SHIPMENT DOCUMENTATION FLAG"],
    [2406, "A"  , false, 0..1  , nil, "DEFERRED LABEL FLAG"],
    [2407, "A"  , false, 0..10 , nil, "RECIPIENT LOCATION NUMBER"],
    [2408, "A/N", false, 0..20 , nil, "IPD OVERNIGHT DOCUMENTS TRACKING NUMBER"],
    [2413, "A"  , false, 0..1  , nil, "ALL METERS FLAG"],
    [2416, "N"  , false, 0..2  , nil, "ANCILLARY ENDORSEMENTS"],
    [2417, "N"  , false, 0..2  , nil, "SMARTPOST SERVICE TYPE/POSTAL INDICIA (OBSOLETE)"],
    [2418, "A/N", false, 0..30 , nil, "DELIVERY CONFIRMATION BARCODE"],
    [2419, "N"  , true , 0..8  , 2  , "C.O.D. VALUE OF PACKAGE"],
    [2420, "A"  , false, 0..35 , nil, "SHIPPER ADDRESS LINE 3"],
    [2421, "A"  , false, 0..35 , nil, "RETURN ADDRESS LINE 3"],
    [2422, "N"  , true , 0..30 , nil, "C.O.D. ARTICLE NUMBER"],
    [2423, "A"  , false, 0..1  , nil, "UPLOAD FLAG"],
    [2424, "N"  , false, 0..1  , nil, "RECIPIENT TAX ID TYPE"],
    [2425, "N"  , false, 0..5  , nil, "SMARTPOST CUSTOMER ID"],
    [2427, "A"  , false, 0..1  , nil, "CONSOLIDATED COMMODITY FILE FLAG"],
    [2428, "N"  , false, 0..1  , nil, "CONSOLIDATED COMMODITY FILE FORMAT"],
    [2429, "N"  , true , 0..2  , nil, "CUSTOM LABEL TYPE INDICATOR"],
    [2430, "N"  , true , 0..5  , nil, "CUSTOM LABEL X POSITION"],
    [2431, "N"  , true , 0..5  , nil, "CUSTOM LABEL Y POSITION"],
    [2432, "A"  , true , 0..400, nil, "CUSTOM LABEL TEXT STRING FORMAT"],
    [2433, "A"  , false, 0..35 , nil, "ARGUMENTS"],
    [2434, "A"  , false, 0..3  , nil, "THERMAL FONT ID"],
    [2436, "A"  , true , 0..3  , nil, "GRAPHIC LOCATION"],
    [2437, "N"  , true , 0..5  , nil, "ENDING X"],
    [2438, "N"  , true , 0..5  , nil, "CUSTOM LABEL ENDING Y POS"],
    [2439, "N"  , true , 0..5  , nil, "BAR CODE HEIGHT"],
    [2440, "N"  , true , 0..5  , nil, "THIN BAR WIDTH/MILSPEC"],
    [2441, "N"  , true , 0..2  , nil, "BAR CODE TYPE"],
    [2442, "A/N", false, 0..30 , nil, "RFID/EPC NUMBER"],
    [2444, "A"  , false, 0..1  , nil, "NON-SHIPPING LABEL FLAG"],
    [2448, "A"  , true , 0..1  , nil, "RECIPIENT IDENTIFICATION TYPE"],
    [2550, "A"  , false, 0..2  , nil, "FIELD 2550"],
    [2551, "N"  , false, 0..1  , nil, "FIELD 2551"],
    [2600, "N"  , false, 0..2  , nil, "PACKAGE ASSOCIATION AND PRINT MODE"],
    [2700, "A"  , false, 0..1  , nil, "RETURN SHIPPER INSTRUCTIONS"],
    [2702, "AKE", false, 0..200, nil, "PRINT RETURN MESSAGE"],
    [2703, "N"  , false, 0..2  , nil, "CUSTOMIZED TIME IN TRANSIT"],
    [2713, "N"  , false, 0..2  , nil, "NUMBER OF CRNS"],
    [2800, "N"  , false, 0..11 , 2  , "FIELD 2800"],
    [2801, "N"  , false, 0..4  , nil, "HUB ID"],
    [2802, "A"  , false, 0..1  , nil, "NON-MACHINABLE TAG"],
    [2803, "N"  , false, 0..11 , 2  , "NON-MACHINABLE SURCHARGE"],
    [2804, "N"  , false, 0..11 , 2  , "DELIVERY CONFIRMATION SERVICE SURCHARGE"],
    [2805, "A"  , false, 0..1  , nil, "ETD INDICATOR"],
    [2817, "AKE", true , 0..40 , nil, "DOCUMENT REFERENCE ID"],
    [2818, "N"  , true , 0..1  , nil, "FIELD 2818"],
    [2819, "AKE", true , 0..255, nil, "ETD DOCUMENT FILENAME"],
    [2820, "A"  , false, 0..1  , nil, "ETD WAIT FOR CONFIRMATION"],
    [2821, "A"  , true , 0..1  , nil, "ETD DOCUMENT GENERATION"],
    [2822, "N"  , true , 0..2  , nil, "ETD DOCUMENT STATUS"],
    [2831, "N"  , false, 0..1  , nil, "FIELD 2831"],
    [2833, "A"  , false, 0..1  , nil, "FIELD 2833"],
    [2848, "N"  , false, 0..5  , nil, "ALTERNATE DYNAMIC SURCHARGE AND/OR FEES CODE"],
    [2849, "N"  , false, 0..11 , 2  , "ALTERNATE DYNAMIC SURCHARGE AND/OR FEES VALUE"],
    [2850, "A/N", true , 0..5  , nil, "DISCOUNT OPTION SETTINGS"],
    [2851, "N"  , false, 0..13 , 2  , "ALTERNATE BONUS DISCOUNT AMOUNT"],
    [2852, "N"  , false, 0..13 , 2  , "ALTERNATE EARNED DISCOUNT AMOUNT"],
    [2853, "N"  , false, 0..13 , 2  , "FIELD 2853"],
    [2854, "N"  , false, 0..13 , 2  , "ALTERNATE BASE CHARGE"],
    [2855, "N"  , false, 0..13 , 2  , "ALTERNATE DISCOUNT AMOUNT"],
    [2856, "N"  , false, 0..13 , 2  , "ALTERNATE TOTAL SURCHARGE"],
    [2857, "N"  , false, 0..13 , 2  , "ALTERNATE NET CHARGE AMOUNT"],
    [2858, "N"  , false, 0..13 , 2  , "ALTERNATE FUEL SURCHARGE"],
    [2859, "N"  , false, 0..13 , 2  , "ALTERNATE DECLARED VALUE SURCHARGE"],
    [2860, "N"  , false, 0..3  , nil, "ALTERNATE MINIMUM PACKAGE CHARGE"],
    [2861, "N"  , false, 0..13 , 2  , "ALTERNATE OUT OF DELIVERY SURCHARGE"],
    [2862, "N"  , false, 0..13 , 2  , "ALTERNATE SATURDAY PICKUP SURCHARGE"],
    [2863, "N"  , false, 0..13 , 2  , "ALTERNATE SATURDAY DELIVERY SURCHARGE"],
    [2864, "N"  , false, 0..13 , 2  , "ALTERNATE DANGEROUS GOODS/HAZMAT SURCHARGE"],
    [2865, "N"  , false, 0..13 , 2  , "ALTERNATE RESIDENTIAL SURCHARGE"],
    [2866, "N"  , false, 0..13 , 2  , "ALTERNATE C.O.D SURCHARGE"],
    [2867, "N"  , false, 0..13 , 2  , "ALTERNATE OUTSIDE PICKUP AREA (OPA) SURCHARGE"],
    [2868, "N"  , false, 0..13 , 2  , "ALTERNATE INSIDE PICKUP SURCHARGE"],
    [2869, "N"  , false, 0..13 , 2  , "ALTERNATE INSIDE DELIVERY SURCHARGE"],
    [2870, "N"  , false, 0..13 , 2  , "ALTERNATE DELIVERY AREA SURCHARGE"],
    [2871, "N"  , false, 0..13 , 2  , "ALTERNATE PRIORITY ALERT SURCHARGE"],
    [2872, "N"  , false, 0..13 , 2  , "ALTERNATE RATE RETURN CODE"],
    [2873, "N"  , false, 0..13 , 2  , "ALTERNATE RATE CURRENCY TYPE"],
    [2874, "N"  , false, 0..13 , 2  , "ALTERNATE HANDLING CHARGE"],
    [2875, "N"  , false, 0..13 , 2  , "ALTERNATE TOTAL CUSTOMER HANDLING CHARGE"],
    [2876, "N"  , false, 0..13 , 2  , "ALTERNATE OVERSIZE SURCHARGE"],
    [2877, "N"  , false, 0..13 , 2  , "ALTERNATE NONSTANDARD CONTAINER SURCHARGE"],
    [2878, "N"  , false, 0..13 , 2  , "ALTERNATE OFFSHORE SURCHARGE AMOUNT"],
    [2879, "N"  , false, 0..13 , 2  , "ALTERNATE ADDITIONAL HANDLING SURCHARGE"],
    [2880, "N"  , false, 0..13 , 2  , "ALTERNATE DRY ICE SURCHARGE"],
    [2881, "N"  , false, 0..13 , 2  , "ALTERNATE EMAIL LABEL SURCHARGE"],
    [2882, "N"  , false, 0..13 , 2  , "ALTERNATE PRINT RETURN LABEL SURCHARGE"],
    [2883, "N"  , false, 0..13 , 2  , "ALTERNATE THIRD PARTY CONSIGNEE SURCHARGE (TPC)"],
    [2884, "N"  , false, 0..13 , 2  , "ALTERNATE EUROPE FIRST SURCHARGE"],
    [2885, "N"  , false, 0..13 , 2  , "ALTERNATE RESIDENTIAL RURAL SURCHARGE"],
    [2886, "N"  , false, 0..13 , 2  , "ALTERNATE DATE CERTAIN DELIVERY SURCHARGE"],
    [2887, "N"  , false, 0..13 , 2  , "ALTERNATE APPOINTMENT DELIVERY SURCHARGE"],
    [2888, "N"  , false, 0..13 , 2  , "ALTERNATE EVENING DELIVERY SURCHARGE"],
    [2889, "N"  , false, 0..13 , 2  , "ALTERNATE GOODS AND SERVICES SALES TAX (GST)"],
    [2890, "N"  , false, 0..13 , 2  , "ALTERNATE QUEBEC SALES TAX (QST)"],
    [2891, "N"  , false, 0..13 , 2  , "ALTERNATE HARMONIZED SALES TAX (HST)"],
    [2892, "N"  , false, 0..13 , 2  , "ALTERNATE NET FREIGHT CHARGE BEFORE CA TAXES"],
    [2893, "N"  , false, 0..13 , 2  , "ALTERNATE TOTAL SURCHARGE BEFORE CA TAXES"],
    [2894, "N"  , false, 0..13 , 2  , "ALTERNATE TOTAL CUSTOMER HANDLING BEFORE CA TAXES"],
    [2895, "N"  , false, 0..13 , 2  , "ALTERNATE MEXICO IVA TAX"],
    [2896, "N"  , false, 0..13 , 2  , "ALTERNATE NON-MACHINABLE SURCHARGE"],
    [2897, "N"  , false, 0..13 , 2  , "ALTERNATE DELIVERY CONFIRMATION SERVICE SURCHARGE"],
    [2898, "N"  , false, 0..13 , 2  , "ALTERNATE SIGNATURE OPTION FEE"],
    [2917, "A/N", false, 0..400, nil, "2D BARCODE"],
    [2920, "A"  , false, 0..3  , nil, "C.O.D. CURRENCY TYPE"],
    [2931, "N"  , false, 0..5  , nil, "NUMBER OF PACKAGES"],
    [2975, "A"  , false, 0..1  , nil, "MASK ACCOUNT NUMBER"],
    [2990, "N"  , false, 0..3  , nil, "PRINTER DPI SETTING"],
    [3000, "N"  , false, 0..2  , nil, "C.O.D. COLLECTION TYPE"],
    [3001, "A/N", false, 0..30 , nil, "SHIPMENT PURCHASE ORDER NUMBER"],
    [3002, "A/N", false, 0..30 , nil, "SHIPMENT INVOICE NUMBER"],
    [3003, "A"  , false, 0..30 , nil, "SHIPMENT CUSTOMER REFERENCE INFORMATION"],
    [3010, "A"  , false, 0..1  , nil, "OVERSIZE I FLAG"],
    [3011, "A"  , false, 0..1  , nil, "OVERSIZE II FLAG"],
    [3013, "N"  , false, 0..11 , 2  , "NONSTANDARD CONTAINER SURCHARGE"],
    [3014, "A"  , true , 0..1  , nil, "E.C.O.D. FLAG"],
    [3018, "A"  , false, 0..1  , nil, "NONSTANDARD CONTAINER FLAG"],
    [3019, "A"  , false, 0..1  , nil, "FIELD 3019"],
    [3020, "N"  , false, 0..1  , nil, "FEDEX HOME DELIVERY TYPE"],
    [3021, "A"  , false, 0..90 , nil, "SPECIAL DELIVERY INSTRUCTIONS"],
    [3023, "N"  , false, 0..8  , nil, "FEDEX HOME DELIVERY DATE"],
    [3024, "N"  , false, 0..15 , nil, "FEDEX HOME DELIVERY PHONE NUMBER"],
    [3025, "A"  , true , 0..4  , nil, "CARRIER CODE"],
    [3027, "N"  , false, 0..11 , 2  , "RESIDENTIAL RURAL SURCHARGE"],
    [3028, "N"  , false, 0..9  , nil, "GROUND ACCOUNT NUMBER"],
    [3035, "N"  , false, 0..15 , nil, "SHIPALERT/PRE-DELIVERY ALERT FAX NUMBER"],
    [3039, "N"  , false, 0..11 , 2  , "DATE CERTAIN DELIVERY SURCHARGE"],
    [3040, "N"  , false, 0..11 , 2  , "APPOINTMENT DELIVERY SURCHARGE"],
    [3041, "N"  , false, 0..11 , 2  , "EVENING DELIVERY SURCHARGE"],
    [3045, "A/N", false, 0..1  , nil, "FEDEX GROUND C.O.D. RETURN REFERENCE INDICATOR"],
    [3056, "AKE", true , 0..30 , nil, "GND PACKAGE LEVEL PURCHASE ORDER NUMBER"],
    [3057, "A/N", true , 0..30 , nil, "PACKAGE INVOICE NUMBER"],
    [3058, "N"  , false, 0..2  , nil, "TIME IN TRANSIT"],
    [3059, "A"  , false, 0..30 , nil, "SHIPMENT IDENTIFIER NUMBER"],
    [3060, "N"  , false, 0..4  , nil, "FIELD 3060"],
    [3061, "N"  , false, 0..2  , nil, "FEDEX GROUND PACKAGE REPORTING"],
    [3062, "N"  , false, 0..1  , nil, "RATE QUOTE TYPE"],
    [3063, "A"  , false, 0..26 , nil, "96 UCC/EAN BAR CODE DATA"],
    [3064, "A"  , false, 0..350, nil, "PDF-417 BAR CODE STRING"],
    [3065, "A"  , false, 0..8  , nil, "POSTAL CODE BAR CODE STRING"],
    [3072, "A/N", false, 0..50 , nil, "TYPE DOT LABEL(S) REQUIRED, LTD. QTY., OR EXEMPTION NUMBER"],
    [3073, "N"  , false, 0..3  , nil, "GROUND/FHD SERVICE CODE"],
    [3075, "N"  , false, 0..15 , nil, "HAZMAT EMERGENCY PHONE NUMBER"],
    [3076, "N"  , false, 0..11 , 2  , "LIST NONSTANDARD CONTAINER SURCHARGE"],
    [3079, "N"  , false, 0..11 , 2  , "LIST EVENING DELIVERY SURCHARGE"],
    [3080, "N"  , false, 0..11 , 2  , "LIST DATE CERTAIN DELIVERY SURCHARGE"],
    [3082, "N"  , false, 0..11 , 2  , "LIST APPOINTMENT DELIVERY SURCHARGE"],
    [3084, "N"  , false, 0..11 , 2  , "LIST RESIDENTIAL RURAL SURCHARGE"],
    [3120, "A"  , false, 0..12 , nil, "DOC-TAB HEADING"],
    [3121, "N"  , false, 0..4  , nil, "DOC-TAB VALUES"],
    [3122, "A"  , true , 0..1  , nil, "DOC-TAB REFERENCE"],
    [3124, "N"  , false, 0..1  , nil, "FEDEX GROUND OVERSIZE INDICATOR"],
    [3125, "N"  , false, 0..1  , nil, "DCS TYPE – DESTINATION CONTROL STATEMENT PRINT TYPE"],
    [3126, "A/N", false, 0..11 , nil, "DOS COUNTRY CODE(S)"],
    [3127, "A/N", true , 0..25 , nil, "DOS END USER"],
    [3128, "A/N", true , 0..10 , nil, "BUILD DATE"],
    [3129, "A/N", true , 0..256, nil, "COMPONENT NAME"],
    [3130, "N"  , false, 0..1  , nil, "AIR WAYBILL LABEL INDICATOR"],
    [3135, "A/N", false, 0..10 , nil, "BILLING NUMBER"],
    [3144, "A/N", false, 0..5  , nil, "IGDD HUB CODE"],
    [3145, "A"  , false, 0..1  , nil, "HAL LOCATION TYPE"],
    [3147, "N"  , false, 0..20 , nil, "HAL LOCATION PHONE NUMBER"],
    [3148, "A/N", false, 0..35 , nil, "HAL ADDRESS LINE 2"],
    [3149, "A"  , false, 0..40 , nil, "HAL LOCATION BRANDED NAME"],
    [3180, "A"  , false, 0..1  , nil, "EXPRESS EXTENDED FUTURE ALLOWED"],
    [3181, "A"  , false, 0..1  , nil, "USE DYNAMIC SURCHARGING"],
    [3187, "N"  , false, 0..11 , 2  , "ALTERNATE FREIGHT TO COLLECT SURCHARGE"],
    [3188, "N"  , false, 0..11 , 2  , "LIST FREIGHT TO COLLECT SURCHARGE"],
    [3189, "N"  , false, 0..11 , 2  , "FREIGHT TO COLLECT SURCHARGE"],
    [3190, "A"  , false, 0..1  , nil, "FREIGHT TO COLLECT FLAG"],
    [3193, "N"  , false, 0..12 , nil, "FIELD 3193"],
    [3194, "N"  , false, 0..12 , nil, "RECIPIENT STATE TAX ID"],
    [3198, "A/N", false, 0..30 , nil, "DOMESTIC REGULATORY REFERENCE NUMBER"],
    [3199, "A/N", true , 0..50 , nil, "DOMESTIC CONTENT DESCRIPTION"],
    [3204, "A"  , false, 0..1  , nil, "DELIVERY CONFIRMATION FLAG"],
    [3231, "A"  , false, 0..1  , nil, "RESIDENTIAL PICKUP FLAG"],
    [3309, "A"  , false, 0..1  , nil, "TPC FLAG"],
    [3370, "A/N", false, 0..255, nil, "IP ADDRESS"],
    [3371, "A"  , false, 0..1  , nil, "ADDRESS TYPE"],
    [3372, "N"  , false, 0..4  , nil, "PORT"],
    [3373, "A"  , false, 0..30 , nil, "BROADCAST LISTENER NAME"],
    [3374, "A"  , false, 0..9  , nil, "BROADCAST EVENTS"],
    [4027, "N"  , false, 0..11 , 2  , "LIST THIRD PARTY CONSIGNEE SURCHARGE"],
    [4028, "A"  , false, 0..3  , nil, "LIST RATE CURRENCY TYPE"],
    [4029, "N"  , false, 0..11 , 2  , "LIST OFFSHORE SURCHARGE"],
    [4030, "N"  , false, 0..11 , 2  , "LIST EUROPE FIRST SURCHARGE"],
    [4037, "N"  , false, 0..12 , 5  , "DANGEROUS GOODS COMMODITY QUANTITY (HIGH PRECISION)"],
    [4099, "A"  , false, 0..3  , nil, "TERMS OF SALE DESCRIPTION"],
    [4565, "N"  , false, 0..11 , 2  , "MINIMUM PACKAGE CHARGE"],
    [4568, "N"  , false, 0..11 , 2  , "LIST MINIMUM PACKAGE CHARGE"],
    [4574, "N"  , false, 0..1  , nil, "IPD/IDF MPS COMMODITY SET INDICATOR"],
    [4639, "A"  , false, 0..35 , nil, "PAYOR/BILL TO - ADDRESS LINE 1"],
    [4641, "A"  , false, 0..35 , nil, "PAYOR/BILL TO - CITY"],
    [4647, "A"  , false, 0..35 , nil, "PAYOR/BILL TO - COMPANY NAME"],
    [4648, "A"  , false, 0..15 , nil, "PAYOR/BILL TO - POSTAL CODE"],
    [4649, "A"  , false, 0..2  , nil, "PAYOR/BILL TO - STATE/PROVINCE"],
    [4683, "AKE", false, 0..25 , nil, "BILL OF LADING NUMBER"],
    [4889, "N"  , false, 0..11 , 2  , "LIST NET FREIGHT CHARGE BEFORE CANADA TAXES"],
    [4890, "N"  , false, 0..11 , 2  , "TOTAL SURCHARGE AMOUNT BEFORE CANADA TAXES"],
    [4891, "N"  , false, 0..11 , 2  , "LIST TOTAL SURCHARGE AMOUNT BEFORE CANADA TAXES"],
    [4892, "N"  , false, 0..11 , 2  , "TOTAL CUSTOMER HANDLING CHARGE BEFORE CANADA TAXES"],
    [4893, "N"  , false, 0..11 , 2  , "LIST TOTAL CUSTOMER HANDLING CHARGE BEFORE CANADA TAXES"],
    [4903, "A/N", true , 0..20 , nil, "HAZMAT PACKAGE QUANTITY AND TYPE"],
    [4912, "N"  , true , 0..5  , nil, "ADDITIONAL HANDLING SURCHARGE TYPE"],
    [4913, "N"  , true , 0..5  , nil, "LIST ADDITIONAL HANDLING SURCHARGE TYPE"],
    [4914, "N"  , true , 0..11 , 2  , "DRY ICE SURCHARGE"],
    [4915, "N"  , true , 0..11 , 2  , "LIST DRY ICE SURCHARGE"],
    [4922, "N"  , false, 0..11 , 2  , "FIELD 4922"],
    [4923, "N"  , false, 0..11 , 2  , "FIELD 4923"],
    [4924, "N"  , false, 0..11 , 2  , "FIELD 4924"],
    [4925, "N"  , false, 0..11 , 2  , "FIELD 4925"],
    [4926, "N"  , false, 0..30 , nil, "PREASSIGNED SECONDARY TRACKING NUMBER"],
    [4927, "N"  , false, 0..30 , nil, "DELIVERY CONFIRMATION TRACKING NUMBER"],
    [4031, "N"  , false, 0..11 , 2  , "FULLY REGULATED DANGEROUS GOODS (FDG) SURCHARGE"],
    [4032, "N"  , false, 0..11 , 2  , "LIMITED QUANTITIES DANGEROUS GOODS (LDG) SURCHARGE"],
    [4033, "N"  , false, 0..11 , 2  , "LIST FULLY REGULATED DANGEROUS GOODS (FDG) SURCHARGE"],
    [4034, "N"  , false, 0..11 , 2  , "LIST LIMITED QUANTITIES DANGEROUS GOODS (LDG) SURCHARGE "],
    [4035, "N"  , false, 0..11 , 2  , "ALTERNATE FULLY REGULATED DANGEROUS GOODS (FDG) SURCHARGE"],
    [4036, "N"  , false, 0..11 , 2  , "ALTERNATE LIMITED QUANTITIES DANGEROUS GOODS (LDG) SURCHARGE"],
    [4937, "N"  , true , 0..1  , nil, "SQE INDICATOR TAG"],
    [4938, "N"  , true , 0..1  , nil, "NON HAZARDOUS BATTERY INDICATOR"],
    [4939, "AKE", true , 0..35 , nil, "FIELD 4939"],
    [4941, "N"  , false, 0..10 , 2  , "INNER RECEPTACLE QUANTITY"],
    [4942, "A"  , false, 0..4  , nil, "INNER RECEPTACLE UNIT"],
    [4943, "A"  , false, 0..10 , nil, "TUNNEL RESTRICTION CODE"],
    [4944, "A"  , false, 0..255, nil, "ATTRIBUTES"],
    [4945, "A"  , false, 0..10 , nil, "MASS POINTS"],
    [4948, "A"  , false, 0..1  , nil, "ADR REGULATION INDICATOR"],
    [4949, "A"  , false, 0..4  , nil, "ADR LICENSE NUMBER"],
    [4950, "N"  , false, 0..4  , 1  , "CRITICALITY SAFETY INDEX"],
    [5542, "N"  , false, 0..2  , nil, "CUSTOMS PROCESSING TYPE"],
    [5543, "AKE", false, 0..25 , nil, "CUSTOMS PROCESSING REASON DESCRIPTION"],
    [5544, "N"  , true , 0..20 , nil, "ASSOCIATED OUTBOUND SHIPMENT TRACKING NUMBER"],
    [5545, "N"  , false, 0..8  , nil, "ASSOCIATED OUTBOUND SHIPMENT SHIP DATE"],
    [5546, "A"  , false, 0..2  , nil, "RETURN INSTRUCTIONS LANGUAGE CODE"],
    [5547, "A"  , false, 0..3  , nil, "RETURN INSTRUCTIONS FORMAT INDICATOR"],
    [5548, "A"  , false, 0..2  , nil, "RETURN INSTRUCTIONS LANGUAGE LOCALE CODE"],
    [5549, "A/N", false, 0..255, nil, "RETURN INSTRUCTIONS PRINTER ID"],
    [5550, "A/N", false, 0..255, nil, "RETURN INSTRUCTIONS DIRECTORY PATH"],
    [5560, "A"  , false, 0..1  , nil, "RETURNS CLEARANCE"],
    [5592, "N"  , false, 0..1  , nil, "LABEL PRINT ORDER"],
    [5654, "A"  , false, 0..1  , nil, "GLOBAL RETURNS INDICATOR"],
    [5563, "A/N", false, 0..1  , nil, "MERCHANT NOTIFICATION INDICATOR"],
    [5569, "A/N", false, 0..120, nil, "MERCHANT NOTIFICATION E-MAIL ADDRESS"],
    [5575, "A"  , false, 0..2  , nil, "MERCHANT NOTIFICATION E-MAIL LANGUAGE"],
    [5581, "A"  , false, 0..2  , nil, "MERCHANT NOTIFICATION E-MAIL LANGUAGE LOCALE CODE"],
    [5587, "A"  , false, 0..2  , nil, "RETURN SHIPPER NOTIFICATION LANGUAGE"],
    [5588, "A"  , false, 0..2  , nil, "RETURN SHIPPER NOTIFICATION LANGUAGE LOCALE CODE"],
    [5589, "A"  , false, 0..1  , nil, "SUPPRESS ADDITIONAL LANGUAGE FOR RETURN SHIPPER E-MAIL"],
    [5590, "A"  , false, 0..1  , nil, "SUPPRESS ADDITIONAL LANGUAGE FOR RETURN INSTRUCTIONS"],
    [5591, "N"  , true , 0..3  , nil, "SUGGESTED DOCUMENTS"],
    [5593, "A"  , false, 0..1  , nil, "RETURN SHIPPER ALLOW MODIFICATION"],
    [5594, "AKE", false, 0..255, nil, "MERCHANT DOCUMENT NAME"],
    [5599, "AKE", false, 0..255, nil, "MERCHANT DOCUMENT LOCATION"],
    [5600, "A/N", false, 0..1  , nil, "SENDER TENDERED NOTIFICATION FLAG"],
    [5601, "A/N", false, 0..1  , nil, "RECIPIENT TENDERED NOTIFICATION FLAG"],
    [5602, "A/N", false, 0..1  , nil, "BROKER TENDERED NOTIFICATION FLAG"],
    [5603, "A/N", true , 0..1  , nil, "OTHER TENDERED NOTIFICATION FLAG"],
    [5605, "A/N", false, 0..25 , nil, "UPLOADED DOCUMENT ID"],
    [5606, "A/N", false, 0..8  , nil, "UPLOAD DOCUMENT EXPIRATION DATE"],
    [5700, "N"  , false, 0..1  , nil, "ALCOHOL RECIPIENT TYPE"],
    [5701, "N"  , false, 0..1  , nil, "FIELD 5701"],
    [5752, "N"  , false, 0..1  , nil, "AWB REQUIRED COPIES"],
    [5790, "N"  , false, 0..1  , nil, "LETTERHEAD/SIGNATURE REQUIRED"],
    [6100, "A"  , false, 0..1  , nil, "LTL FREIGHT FLAG"],
    [6101, "N"  , true , 0..4  , nil, "SHIPMENT VOLUME"],
    [6102, "N"  , false, 0..16 , nil, "P.O. BOX"],
    [6103, "A"  , false, 0..1  , nil, "C.O.D. REMIT PAYOR"],
    [6104, "N"  , false, 0..1  , nil, "C.O.D. FEE PAYOR"],
    [6105, "N"  , false, 0..3  , 1  , "NMFC CLASS"],
    [6106, "AKE", false, 0..9  , nil, "NMFC ITEM #"],
    [6107, "N"  , false, 0..1  , nil, "SHIPMENT TERMS"],
    [6108, "A"  , false, 0..25 , nil, "SHIPPER NUMBER 1"],
    [6109, "A"  , false, 0..25 , nil, "SHIPPER NUMBER 2"],
    [6110, "A"  , false, 0..19 , nil, "FIELD 6110"],
    [6111, "N"  , false, 0..3  , nil, "TOTAL PALLETS"],
    [6112, "A"  , true , 0..1  , nil, "DIGITAL LETTERHEAD INDICATOR"],
    [6113, "A"  , true , 0..1  , nil, "DIGITAL SIGNATURE INDICATOR"],
    [6114, "A/N", true , 0..255, nil, "DIGITAL LETTERHEAD IMAGE PATH"],
    [6115, "A/N", true , 0..255, nil, "DIGITAL SIGNATURE IMAGE PATH"],
    [6116, "N"  , false, 0..1  , nil, "FREIGHT PAYOR ROLE/TYPE"],
    [6117, "N"  , false, 0..3  , nil, "LTL FREIGHT LABEL NUMBER OF COPIES"],
    [6118, "A"  , false, 0..2  , nil, "FXNL BILLING COUNTRY CODE"],
    [6119, "A/N", false, 0..35 , nil, "FXNL BILLING COMPANY NAME"],
    [6120, "A/N", false, 0..35 , nil, "FXNL BILLING ADDRESS LINE 1"],
    [6121, "A/N", false, 0..35 , nil, "FXNL BILLING ADDRESS LINE 2"],
    [6122, "A/N", false, 0..35 , nil, "FXNL BILLING CITY"],
    [6123, "A"  , false, 0..14 , nil, "FXNL BILLING STATE/PROVINCE"],
    [6124, "A/N", false, 0..16 , nil, "FXNL BILLING ZIP/POSTAL CODE"],
    [6125, "N"  , false, 0..15 , nil, "FXNL BILLING TELEPHONE NUMBER"],
    [6126, "N"  , false, 0..9  , nil, "FXNL BILLING TELEPHONE EXTENSION"],
    [6127, "A/N", false, 0..120, nil, "FXNL BILLING EMAIL ID"],
    [6128, "A"  , false, 0..2  , nil, "FXF BILLING COUNTRY CODE"],
    [6129, "A/N", false, 0..35 , nil, "FXF BILLING COMPANY NAME"],
    [6130, "A/N", false, 0..35 , nil, "FXF BILLING ADDRESS LINE 1"],
    [6131, "A/N", false, 0..35 , nil, "FXF BILLING ADDRESS LINE 2"],
    [6132, "A"  , false, 0..35 , nil, "FXF BILLING CITY"],
    [6133, "A"  , false, 0..14 , nil, "FXF BILLING STATE/PROVINCE"],
    [6134, "A/N", false, 0..16 , nil, "FXF BILLING ZIP/POSTAL CODE"],
    [6135, "N"  , false, 0..15 , nil, "FXF BILLING TELEPHONE NUMBER"],
    [6136, "N"  , false, 0..9  , nil, "FXF BILLING TELEPHONE EXTENSION"],
    [6137, "A/N", false, 0..120, nil, "FXF BILLING EMAIL ID"],
    [6138, "N"  , false, 0..9  , nil, "FXNL ACCOUNT NUMBER"],
    [6139, "N"  , false, 0..9  , nil, "FXF ACCOUNT NUMBER"],
    [6140, "N"  , false, 0..9  , nil, "COD RETURN PHONE EXTENSION"],
    [6141, "A"  , false, 0..9  , nil, "COD REMIT TO COUNTRY"],
    [6142, "N"  , false, 0..9  , nil, "TOTAL HANDLING UNITS"],
    [6151, "N"  , false, 0..1  , nil, "LIFTGATE AT PICKUP TERM"],
    [6152, "N"  , false, 0..1  , nil, "LIFTGATE AT DELIVERY TERM"],
    [6153, "N"  , false, 0..1  , nil, "INSIDE PICKUP TERM"],
    [6154, "N"  , false, 0..1  , nil, "INSIDE DELIVERY TERM"],
    [6155, "N"  , true , 0..1  , nil, "GUARANTEED SERVICES UPGRADE"],
    [6156, "N"  , false, 0..8  , nil, "GUARANTEED EXACT TIME"],
    [6157, "N"  , false, 0..1  , nil, "CUSTOM DELIVERY INDICATOR"],
    [6158, "N"  , false, 0..8  , nil, "CUSTOM DELIVERY TIME"],
    [6159, "N"  , false, 0..8  , nil, "CUSTOM DELIVERY START DATE"],
    [6160, "N"  , false, 0..8  , nil, "CUSTOM DELIVERY END DATE"],
    [6161, "N"  , false, 0..8  , nil, "CUSTOM DELIVERY DATE"],
    [6162, "N"  , false, 0..2  , nil, "EMAIL DOCUMENTS INDICATOR"],
    [6163, "N"  , false, 0..2  , nil, "EMAIL DOCUMENTS TO"],
    [6166, "N"  , true , 0..2  , nil, "LTL PACKAGING"],
    [6167, "N"  , false, 0..1  , nil, "BOL FORMAT"],
    [6168, "A"  , false, 0..1  , nil, "LTL FREIGHT PICKUP REQUESTED FLAG"],
    [6169, "N"  , false, 0..8  , nil, "REQUESTED PICKUP DATE"],
    [6170, "N"  , false, 0..8  , nil, "DOCK READY TIME"],
    [6171, "N"  , false, 0..8  , nil, "DOCK CLOSE TIME"],
    [6172, "A"  , false, 0..35 , nil, "LTL PICKUP SUBMITTED BY CONTACT"],
    [6173, "N"  , false, 0..15 , nil, "LTL PICKUP SUBMITTED BY TELEPHONE"],
    [6174, "A/N", false, 0..120, nil, "LTL PICKUP SUBMITTED BY EMAIL"],
    [6175, "A"  , false, 0..35 , nil, "AT DOCK CONTACT"],
    [6176, "N"  , false, 0..15 , nil, "AT DOCK TELEPHONE"],
    [6177, "A/N", false, 0..120, nil, "AT DOCK EMAIL"],
    [6178, "A/N", false, 0..35 , nil, "ORIGIN SERVICE CENTER NAME"],
    [6179, "A/N", false, 0..12 , nil, "ORIGIN SERVICE CENTER ALPHA ID"],
    [6180, "A/N", false, 0..35 , nil, "ORIGIN SERVICE CENTER ADDRESS"],
    [6181, "A/N", false, 0..35 , nil, "ORIGIN SERVICE CENTER CITY"],
    [6182, "A"  , false, 0..14 , nil, "ORIGIN SERVICE CENTER STATE/PROVINCE"],
    [6183, "A/N", false, 0..16 , nil, "ORIGIN SERVICE CENTER ZIP/POSTAL"],
    [6184, "A/N", false, 0..2  , nil, "ORIGIN SERVICE CENTER COUNTRY"],
    [6185, "A/N", false, 0..15 , nil, "ORIGIN SERVICE CENTER TELEPHONE"],
    [6186, "A/N", false, 0..15 , nil, "ORIGIN SERVICE CENTER FAX NUMBER"],
    [6187, "A/N", false, 0..35 , nil, "ORIGIN SERVICE CENTER MANAGER NAME"],
    [6188, "A/N", false, 0..4  , nil, "ORIGIN CARRIER CODE"],
    [6189, "A/N", false, 0..35 , nil, "ORIGIN CARRIER NAME"],
    [6190, "A/N", false, 0..35 , nil, "ORIGIN LOCAL SERVICE"],
    [6191, "A/N", true , 0..35 , nil, "DESTINATION SERVICE CENTER NAME"],
    [6192, "A/N", true , 0..12 , nil, "DESTINATION SERVICE CENTER ALPHA ID"],
    [6193, "A/N", true , 0..35 , nil, "DESTINATION SERVICE CENTER ADDRESS"],
    [6194, "A/N", true , 0..35 , nil, "DESTINATION SERVICE CENTER CITY"],
    [6195, "A/N", true , 0..14 , nil, "DESTINATION SERVICE CENTER STATE/PROVINCE"],
    [6196, "A/N", true , 0..16 , nil, "DESTINATION SERVICE CENTER ZIP/POSTAL"],
    [6197, "A/N", true , 0..2  , nil, "DESTINATION SERVICE CENTER COUNTRY"],
    [6198, "A/N", true , 0..15 , nil, "DESTINATION SERVICE CENTER TELEPHONE"],
    [6199, "A/N", true , 0..15 , nil, "DESTINATION SERVICE CENTER FAX NUMBER"],
    [6200, "A/N", true , 0..35 , nil, "DESTINATION SERVICE CENTER MANAGER NAME"],
    [6201, "A/N", true , 0..4  , nil, "DESTINATION CARRIER CODE"],
    [6202, "A/N", true , 0..35 , nil, "DESTINATION CARRIER NAME"],
    [6203, "A/N", true , 0..35 , nil, "DESTINATION LOCAL SERVICE"],
    [6204, "A/N", true , 0..20 , nil, "LTL RATE QUOTE NUMBER"],
    [6205, "A/N", true , 0..20 , nil, "LTL RATE SCALE"],
    [6207, "A/N", true , 0..3  , nil, "LTL FUEL SURCHARGE PERCENT"],
    [6208, "A/N", false, 0..255, nil, "BOL IMAGE FILE PATH"],
    [6209, "A/N", false, 0..255, nil, "ADDRESS LABEL IMAGE FILE PATH"],
    [6210, "A/N", false, 0..35 , nil, "LTL PICKUP SUBMITTED BY COMPANY"],
    [6211, "A/N", false, 0..15 , nil, "LTL DECLARED VALUE UNITS"],
    [6217, "A/N", true , 0..30 , nil, "LTL SURCHARGE TYPE"],
    [6218, "N"  , true , 0..11 , 2  , "LTL SURCHARGE AMOUNT"],
    [6219, "A/N", false, 0..1  , nil, "ARTICLE TYPE"],
    [6220, "N"  , false, 0..11 , 2  , "EXCESS LIABILITY AMOUNT"],
    [6221, "A"  , false, 0..1  , nil, "TERMS AND CONDITIONS FLAG"],
    [6222, "A/N", true , 0..15 , nil, "RATE LEG DESCRIPTION"],
    [6223, "N"  , true , 0..11 , 2  , "RATE LEG SUB-TOTAL"],
    [6224, "N"  , false, 0..9  , nil, "THIRD PARTY ACCOUNT"],
    [6225, "AKE", false, 0..35 , nil, "THIRD PARTY CONTACT NAME"],
    [6226, "AKE", false, 0..35 , nil, "THIRD PARTY COMPANY NAME"],
    [6227, "AKE", false, 0..35 , nil, "THIRD PARTY ADDRESS LINE 1"],
    [6228, "AKE", false, 0..35 , nil, "THIRD PARTY ADDRESS LINE 2"],
    [6229, "A/N", false, 0..35 , nil, "THIRD PARTY CITY"],
    [6230, "A/N", false, 0..35 , nil, "THIRD PARTY STATE/PROVINCE"],
    [6231, "A/N", false, 0..10 , nil, "THIRD PARTY ZIP/POSTAL CODE"],
    [6232, "A"  , false, 0..20 , nil, "THIRD PARTY COUNTRY CODE"],
    [6233, "A/N", false, 0..15 , nil, "THIRD PARTY TELEPHONE NUMBER"],
    [6234, "A/N", false, 0..30 , nil, "EXPORT BROKER CONTACT NAME"],
    [6235, "A/N", false, 0..35 , nil, "EXPORT BROKER COMPANY NAME"],
    [6236, "A/N", false, 0..35 , nil, "EXPORT BROKER ADDRESS LINE 1"],
    [6237, "A/N", false, 0..35 , nil, "EXPORT BROKER ADDRESS LINE 2"],
    [6238, "A/N", false, 0..35 , nil, "EXPORT BROKER CITY"],
    [6239, "A/N", false, 0..14 , nil, "EXPORT BROKER STATE/PROVINCE"],
    [6240, "A/N", false, 0..10 , nil, "EXPORT BROKER ZIP/POSTAL CODE"],
    [6241, "A/N", false, 0..2  , nil, "EXPORT BROKER COUNTRY CODE"],
    [6242, "A/N", false, 0..15 , nil, "EXPORT BROKER TELEPHONE NUMBER"],
    [6243, "AKE", false, 0..25 , nil, "CONSIGNEE ID"],
    [6244, "A/N", false, 0..1  , nil, "VOLUME TYPE"],
    [6246, "A/N", true , 0..450, nil, "LINE ITEM DESCRIPTION"],
    [6247, "AKE", false, 0..35 , nil, "ALTERNATE BILLING CONTACT NAME"],
    [6248, "AKE", false, 0..35 , nil, "ALTERNATE BILLING COMPANY NAME"],
    [6249, "AKE", false, 0..35 , nil, "ALTERNATE BILLING ADDRESS LINE 1"],
    [6250, "AKE", false, 0..35 , nil, "ALTERNATE BILLING ADDRESS LINE 2"],
    [6251, "A/N", false, 0..35 , nil, "ALTERNATE BILLING CITY"],
    [6252, "A/N", false, 0..35 , nil, "ALTERNATE BILLING STATE/PROVINCE"],
    [6253, "A/N", false, 0..16 , nil, "ALTERNATE BILLING ZIP/POSTAL CODE"],
    [6254, "A"  , false, 0..2  , nil, "ALTERNATE BILLING COUNTRY CODE"],
    [6255, "A/N", false, 0..15 , nil, "ALTERNATE BILLING TELEPHONE NUMBER"],
    [6256, "N"  , false, 0..9  , nil, "ALTERNATE BILLING ACCOUNT NUMBER"],
    [6258, "A/N", true , 0..30 , nil, "LTL TAX TYPE"],
    [6259, "N"  , true , 0..11 , 2  , "LTL TAX AMOUNT"],
    [6260, "N"  , true , 0..11 , 2  , "LTL TOTAL TAXES"],
    [6264, "A/N", false, 0..9  , nil, "THIRD PARTY TELEPHONE EXTENSION"],
    [6265, "A/N", false, 0..9  , nil, "THIRD PARTY EMAIL ID"],
    [6266, "N"  , false, 0..20 , nil, "LTL FREIGHT SHIPMENT INDEX"],
    [7000, "A/N", false, 0..33 , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 21"],
    [7001, "A/N", false, 0..33 , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 22"],
    [7002, "A/N", false, 0..33 , nil, "OPERATIONAL INSTRUCTIONS ELEMENT # 23"],
    [7003, "A/N", false, 0..33 , nil, "C.O.D. REMITTER NAME"],
    [7006, "A/N", false, 0..33 , nil, "C.O.D. FINANCIAL INSTITUTION NAME"],
    [7007, "A"  , false, 0..33 , nil, "C.O.D. FINANCIAL INSTITUTION CITY"],
    [7008, "A"  , false, 0..1  , nil, "FREIGHT ON VALUE"],
    [7010, "A"  , false, 0..1  , nil, "HOLIDAY DELIVERY FLAG"],
    [7011, "A"  , false, 0..1  , nil, "SPECIAL DELIVERY FLAG"],
    [7013, "N"  , false, 0..11 , 2  , "FREIGHT ON VALUE SURCHARGE"],
    [7014, "N"  , false, 0..11 , 2  , "LIST FREIGHT ON VALUE SURCHARGE"],
    [7015, "N"  , false, 0..11 , 2  , "ALTERNATE FREIGHT ON VALUE SURCHARGE"],
    [7019, "N"  , false, 0..11 , 2  , "HOLIDAY DELIVERY SURCHARGE"],
    [7020, "N"  , false, 0..11 , 2  , "LIST HOLIDAY DELIVERY SURCHARGE"],
    [7021, "N"  , false, 0..11 , 2  , "ALTERNATE HOLIDAY DELIVERY SURCHARGE"],
    [7022, "N"  , false, 0..11 , 2  , "SPECIAL DELIVERY SURCHARGE"],
    [7023, "N"  , false, 0..11 , 2  , "LIST SPECIAL DELIVERY SURCHARGE"],
    [7024, "N"  , false, 0..11 , 2  , "FIELD 7024"],
    [7026, "N"  , false, 0..11 , 2  , "FIELD 7026"],
    [7027, "N"  , false, 0..11 , 2  , "ALTERNATE SPECIAL DELIVERY SURCHARGE"],
    [7028, "N"  , false, 0..11 , 2  , "EXTRA SURFACE HANDLING SURCHARGE"],
    [7029, "N"  , false, 0..11 , 2  , "LIST EXTRA SURFACE HANDLING SURCHARGE"],
    [7030, "N"  , false, 0..11 , 2  , "ALTERNATE EXTRA SURFACE HANDLING SURCHARGE"],
    [7031, "N"  , false, 0..11 , 2  , "WAYBILL SURCHARGE"],
    [7032, "N"  , false, 0..11 , 2  , "LIST WAYBILL SURCHARGE"],
    [7033, "N"  , false, 0..11 , 2  , "ALTERNATE WAYBILL SURCHARGE"],
    [7213, "A"  , false, 0..1  , nil, "SHIPPER ESTIMATED DELIVERY NOTIFICATION"],
    [7214, "A"  , false, 0..1  , nil, "RECIPIENT ESTIMATED DELIVERY NOTIFICATION "],
    [7215, "A"  , false, 0..1  , nil, "BROKER ESTIMATED DELIVERY NOTIFICATION IS ADDED"],
    [7216, "A"  , false, 0..1  , nil, "OTHER ESTIMATED DELIVERY NOTIFICATION "],
    [7232, "A"  , false, 0..1  , nil, "DANGEROUS GOODS (DG) DATA UPLOAD MODE"],
    [7236, "A"  , false, 0..2  , nil, "HAL COUNTRY"],
    [7245, "N"  , true , 0..1  , nil, "COMMODITY PURPOSE"],
    [7246, "A"  , false, 0..1  , nil, "PRINT IPD/IED/IDF CUSTOMS DETAIL REPORT"],
    [7600, "N"  , false, 0..11 , 2  , "FIELD 7600"],
    [7601, "N"  , false, 0..11 , 2  , "FIELD 7601"],
    [7602, "N"  , false, 0..11 , 2  , "FIELD 7602"],
    [7603, "N"  , false, 0..11 , 2  , "FIELD 7603"],
    [7604, "N"  , false, 0..11 , 2  , "FIELD 7604"],
    [7605, "N"  , false, 0..11 , 2  , "FIELD 7605"],
    [9746, "A/N", false, 0..4  , nil, "FEDEX VENDOR/CLIENT PRODUCT VERSION"],
    [9913, "N"  , false, 0..1  , nil, "SECONDARY BARCODE TYPE"]
  ])
end
